#!/usr/bin/env python3
"""Generate each study page's facts block from the workbook and the records.

WHY NOT study-map.py. The shipped helper is specialised to a different investigation's
schema in two ways that cannot be configured: it matches inquiry rows as
`| NPnn | status | settles | text |` — status BEFORE settles — while the workbook shape
this investigation follows is `id | settles | inputs | procedure | status | produced |
moved`; and its thread vocabulary is the hardcoded list U0..U9, which is not what the
threads here are called. Run against this workbook it reports "21 rows, 0 ran, 0 placed on
a page" and asks for ten pages named U0..U9. Rearranging the workbook to satisfy it would
mean writing the columns in an order the contract does not use, so the facts are generated
here instead, in the documented order and with the real thread names.

Writes only between the `<!-- generated: facts -->` markers. Prose outside them is never
touched.
"""
from __future__ import annotations
import re, sys
from pathlib import Path

INV = Path(__file__).resolve().parents[2]
WORKBOOK = next(INV.glob("INVESTIGATION-*.md"))
START, END = "<!-- generated: facts -->", "<!-- /generated: facts -->"

# Columns, per the workbook contract: id | settles | inputs | procedure | status | produced | moved
ROW = re.compile(r"^\|\s*(NP\d+)\s*\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|\s*$")
FINDING = re.compile(r'<a id="(f\d+)"></a>\s*\n### (F\d+) — (.+?)\n(.*?)(?=\n<a id=|\n## )', re.S)

wb = WORKBOOK.read_text()

rows = {}
for line in wb.splitlines():
    m = ROW.match(line)
    if m:
        rid, settles, inputs, proc, status, produced, moved = (x.strip() for x in m.groups())
        rows[rid] = dict(id=rid, settles=settles, inputs=inputs, procedure=proc,
                         status=status, produced=produced, moved=moved)

findings = {}
for m in FINDING.finditer(wb):
    body = m.group(4)
    setting = re.search(r"\*\*Setting\.\*\*\s*(.+?)\n", body)
    role = re.search(r"\*\*Role:\*\*\s*(.+?)\n", body)
    standing = "refuted" if "❌" in body else "settled"
    findings[m.group(2)] = dict(id=m.group(2), title=m.group(3).strip(),
                                setting=setting.group(1).strip() if setting else "",
                                role=role.group(1).strip() if role else "",
                                standing=standing)

def record_facts(produced: str) -> list[str]:
    """Verdict and key evidence for each record an inquiry row names."""
    out = []
    for name in re.findall(r"raw/([A-Za-z0-9._-]+)\.yaml", produced):
        f = INV / "raw" / f"{name}.yaml"
        if not f.exists():
            continue
        text = f.read_text()
        v = re.search(r"^verdict: (.+)$", text, re.M)
        k = re.search(r"^key_evidence: (.+)$", text, re.M)
        # ⚠️ Accept only ids that are REAL run directories. Absolute paths captured in
        # `command:` and env values contain the harness's own `runs/dockhand-v2/`, which
        # the pattern matches and which is not a run of this investigation — the same
        # confusion that emptied the WROTE edge (action-17).
        runs = sorted({d for d in re.findall(r"runs/([A-Za-z0-9._-]+)/", text)
                       if (INV / "runs" / d).is_dir()})
        out.append((name, v.group(1).strip() if v else "—",
                    (k.group(1).strip() if k else "")[:260], runs))
    return out

def block_for(page: Path) -> str:
    m = re.search(r"^rows:\s*(.*)$", page.read_text(), flags=re.M)
    named = m.group(1).split() if m else []
    lines = ["", f"*Generated by `src/appbay-dockhand/study_facts.py` from "
                 f"`{WORKBOOK.name}` and `raw/`. Do not edit by hand.*", ""]
    for rid in named:
        r = rows.get(rid)
        if not r:
            lines += [f"#### {rid} — not found in the workbook", ""]
            continue
        lines += [f"#### {rid}", "",
                  f"**Settles:** {r['settles']} · **Status:** {r['status']} · "
                  f"**Moved:** {r['moved'] or '—'}", "",
                  f"**Inputs:** {r['inputs']}", "",
                  f"**Procedure, as written:** {r['procedure']}", ""]
        recs = record_facts(r["produced"])
        if recs:
            lines.append("**Records:**")
            for name, verdict, key, runs in recs:
                lines.append(f"- `raw/{name}.yaml` — **{verdict}**: {key}")
                if runs:
                    lines.append(f"  - runs: " + ", ".join(f"`runs/{d}/`" for d in runs))
            lines.append("")
        moved = re.findall(r"\bF(\d+)\b", r["moved"])
        if moved:
            lines.append("**Findings moved:**")
            for fid in moved:
                f = findings.get(f"F{fid}")
                if f:
                    lines.append(f"- **[F{fid}]** {f['title']} — *{f['standing']}*, role: "
                                 f"{f['role'] or '—'}")
                    if f["setting"]:
                        lines.append(f"  - Setting: {f['setting']}")
                else:
                    lines.append(f"- **[F{fid}]** (not found)")
            lines.append("")
    return "\n".join(lines)

changed = 0
for page in sorted((INV / "docs" / "studies").glob("*.md")):
    text = page.read_text()
    if START not in text or END not in text:
        continue
    new = text[:text.index(START) + len(START)] + block_for(page) + text[text.index(END):]
    if new != text:
        page.write_text(new)
        changed += 1
    m = re.search(r"^rows:\s*(.*)$", text, re.M)
    n = len(m.group(1).split()) if m else 0
    print(f"{page.name}: {n} row(s)")

print(f"\nworkbook rows parsed: {len(rows)}   findings parsed: {len(findings)}   pages rewritten: {changed}")
if not rows or not findings:
    sys.exit("refusing to claim success with nothing parsed")
