/**
 * `appbay eject <app>` command.
 *
 * Exports a single app as a self-contained, standalone directory that can
 * be run with `docker compose up -d` without Appbay installed.
 *
 * The ejected directory contains:
 *   - docker-compose.yml (the rendered compose)
 *   - .env (environment variables extracted from the compose)
 *   - Any auxiliary files generated by traits (e.g., Traefik configs)
 *   - README.md with usage instructions
 *
 * This command works offline (imports @appbay/core directly, no server).
 *
 * Exit codes:
 *   0 -- eject succeeded
 *   1 -- eject failed
 */

import { Command } from "commander";
import { join } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { compile, loadProjectVars , detectRuntimeFacts } from "@appbay/core";
import { resolveAppbayHome } from "../utils/appbay-home.js";
import { discoverRunningApps } from "../utils/docker.js";

/**
 * Extract environment variable assignments from a rendered compose YAML.
 *
 * Scans for `environment:` blocks and collects KEY=VALUE pairs. This
 * provides a best-effort .env file for standalone usage.
 */
export function extractEnvVars(rendered: string): string {
  const envVars: Map<string, string> = new Map();
  const lines = rendered.split("\n");
  let inEnvironment = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Detect start of an environment block.
    if (trimmed === "environment:" || trimmed.startsWith("environment:")) {
      inEnvironment = true;
      continue;
    }

    // If we are in an environment block, collect KEY=VALUE items.
    if (inEnvironment) {
      // Environment items are list entries like `- KEY=VALUE`.
      const listMatch = trimmed.match(/^-\s*(.+)=(.*)$/);
      if (listMatch) {
        envVars.set(listMatch[1], listMatch[2]);
        continue;
      }

      // Or mapping entries like `KEY: VALUE`.
      const mapMatch = trimmed.match(/^([A-Z_][A-Z0-9_]*)\s*:\s*(.*)$/);
      if (mapMatch) {
        envVars.set(mapMatch[1], mapMatch[2]);
        continue;
      }

      // If the line is not indented enough or is a different key, exit.
      if (trimmed && !trimmed.startsWith("-") && !trimmed.startsWith("#")) {
        inEnvironment = false;
      }
    }
  }

  // Format as .env file.
  const envLines: string[] = [
    "# Environment variables extracted from Appbay compose",
    "# Review and adjust values before running standalone",
    "",
  ];
  for (const [key, value] of envVars) {
    envLines.push(`${key}=${value}`);
  }

  return envLines.join("\n") + "\n";
}

/**
 * Generate a README for the ejected app directory.
 */
export function generateReadme(appName: string): string {
  return `# ${appName} (Ejected from Appbay)

This compose file was ejected from Appbay and can run standalone with \`docker compose up -d\`.

## Usage

\`\`\`bash
# Start the app
docker compose up -d

# View logs
docker compose logs -f

# Stop the app
docker compose down
\`\`\`

## Notes

- Review the \`.env\` file and adjust values as needed before starting.
- Any auxiliary configuration files are included in this directory.
- This directory is self-contained and does not require Appbay to run.
`;
}

export const ejectCommand = new Command("eject")
  .description("Export an app as a standalone compose directory")
  .argument("<app>", "app name to eject")
  .option(
    "--output <dir>",
    "output directory (default: ./appbay-eject/<appName>/)",
  )
  .action(async (app: string, options: { output?: string }) => {
    const appbayHome = resolveAppbayHome();
    const appsDir = join(appbayHome, "etc", "apps");
    const rendersDir = join(appbayHome, "var", "lib", "renders");
    const stateDir = join(appbayHome, "var", "lib", "state");

    console.log(`Ejecting app "${app}"...\n`);

    // Compile the single app through the full pipeline.
    // Discover running apps so overlays (e.g. when: [ollama]) activate.
    const activeApps = discoverRunningApps();
    let result;
    try {
      // 🚨 projectVars IS NOT OPTIONAL IN PRACTICE. Without it every `${{project.X}}`
      // reference fails to resolve, and essentially every app has one — an ingress trait
      // host is `${{project.DOMAIN}}`. Omitting it made this command fail with
      //   Undefined variable "DOMAIN" in scope "project"
      // on apps that `appbay compile` handled fine, because compile.ts passed it and this
      // did not. Found by the BDD suite (S26 2.2), not by any unit test.
      result = await compile({
        appsDir,
        rendersDir,
        stateDir,
        apps: [app],
        activeApps,
        projectVars: await loadProjectVars(appbayHome),
        // 🚨 WITHOUT THIS THE COMPILER SEES A HOST WITH NO GPU. `compile()` falls back to
        // DEFAULT_RUNTIME_FACTS (`gpu.available: false`) when facts are absent, and NO caller
        // passed them — so the gpu trait threw "no GPU detected on the host" on every host,
        // including one with a working GPU. Measured on an RTX 5070 Ti, driver 580.82.09.
        runtimeFacts: detectRuntimeFacts({ stateDir }),
      });
    } catch (err) {
      console.error(
        `Compile failed: ${err instanceof Error ? err.message : String(err)}`,
      );
      process.exit(1);
    }

    // Check for compile errors.
    if (result.errors.length > 0) {
      console.error("Compile errors:");
      for (const err of result.errors) {
        const prefix = err.appName ? `[${err.appName}]` : "[global]";
        console.error(`  ${prefix} ${err.stage}: ${err.message}`);
      }
      process.exit(1);
    }

    // Verify the app was found and compiled.
    const appResult = result.apps.find((a) => a.appName === app);
    if (!appResult) {
      console.error(`App "${app}" not found in ${appsDir}`);
      process.exit(1);
    }

    // Determine output directory.
    const outputDir = options.output ?? join("appbay-eject", app);
    await mkdir(outputDir, { recursive: true });

    // Write the rendered compose as docker-compose.yml (standard name for standalone use).
    await writeFile(
      join(outputDir, "docker-compose.yml"),
      appResult.rendered,
      "utf-8",
    );

    // Write the .env file with extracted environment variables.
    const envContent = extractEnvVars(appResult.rendered);
    await writeFile(join(outputDir, ".env"), envContent, "utf-8");

    // Write auxiliary files (e.g., Traefik dynamic configs).
    for (const aux of appResult.auxiliaryFiles) {
      const auxPath = join(outputDir, aux.path);
      const auxDir = auxPath.substring(0, auxPath.lastIndexOf("/"));
      if (auxDir) {
        await mkdir(auxDir, { recursive: true });
      }
      await writeFile(auxPath, aux.content, "utf-8");
    }

    // Write the README.
    await writeFile(
      join(outputDir, "README.md"),
      generateReadme(app),
      "utf-8",
    );

    // Report warnings if any.
    if (result.warnings.length > 0) {
      console.log("Warnings:");
      for (const warn of result.warnings) {
        console.log(`  ${warn}`);
      }
      console.log();
    }

    // Summary output.
    const fileCount = 2 + appResult.auxiliaryFiles.length + 1; // compose + .env + aux + README
    console.log(`Ejected "${app}" to ${outputDir}`);
    console.log(`  ${fileCount} files written:`);
    console.log("    docker-compose.yml");
    console.log("    .env");
    for (const aux of appResult.auxiliaryFiles) {
      console.log(`    ${aux.path}`);
    }
    console.log("    README.md");
    console.log(
      `\nRun with: cd ${outputDir} && docker compose up -d`,
    );
  });
