/**
 * Render Caddy Security portal + authentication blocks from typed edge identity config.
 *
 * ⭐ WHY A SEPARATE FILE FROM THE AUTH TRAIT. The trait emits a PER-APP fragment saying
 * "this app requires these roles". This emits the INSTALLATION-WIDE block saying "here is
 * who exists and how they prove it". One is per-app policy; the other is the identity
 * plane. Conflating them is how an app manifest ends up naming an LDAP server.
 *
 * 🚨 SECRET REFERENCES ARE NOT RESOLVED HERE. This renders `{env.LDAP_BIND_PASSWORD}` and
 * the deploy path supplies that variable from the resolved reference. Rendering the value
 * would put a bind password in `var/lib/renders/**`, which is on disk, in the plan diff,
 * and reproducible from inputs — exactly the places a credential must not be.
 */

import type { EdgeIdentityConfig, EdgeIdentityProvider } from "../schemas/edge-identity-providers.js";

/** Env var name carrying a provider's resolved secret at container start. */
export function edgeSecretEnvVar(provider: EdgeIdentityProvider): string | null {
  if (provider.type === "ldap") return `EDGE_LDAP_BIND_PASSWORD_${provider.realm.toUpperCase()}`;
  if (provider.type === "oidc") return `EDGE_OIDC_CLIENT_SECRET_${provider.realm.toUpperCase()}`;
  return null;
}

function renderLocal(p: Extract<EdgeIdentityProvider, { type: "local" }>): string[] {
  return [
    `\tlocal identity store ${p.realm} {`,
    `\t\trealm ${p.realm}`,
    `\t\tpath /config/security/users.json`,
    `\t}`,
  ];
}

/**
 * ⚠️ LDAP is an identity **store**; OAuth/OIDC is an identity **provider**. Caddy Security
 * draws that distinction and rejects the wrong noun with "wrong argument count or
 * unexpected line ending" — a message that points at the realm name, not at the noun.
 * Verified against the pinned binary with `caddy validate`; do not "tidy" these to match.
 */
function renderLdap(p: Extract<EdgeIdentityProvider, { type: "ldap" }>): string[] {
  const out = [
    `\tldap identity store ${p.realm} {`,
    `\t\trealm ${p.realm}`,
    ...p.servers.map((s) => `\t\tservers ${s}${p.tlsInsecureSkipVerify ? " ignore_cert_errors" : ""}`),
    `\t\tattributes {`,
    `\t\t\tname givenName`,
    `\t\t\tsurname sn`,
    `\t\t\tusername sAMAccountName`,
    `\t\t\tmember_of memberOf`,
    `\t\t\temail mail`,
    `\t\t}`,
    `\t\tusername "${p.bindDn}"`,
    `\t\tpassword "{env.${edgeSecretEnvVar(p) ?? ""}}"`,
    `\t\tsearch_base_dn ${p.searchBaseDn}`,
    `\t\tsearch_user_filter "${p.searchUserFilter}"`,
  ];
  if (p.searchGroupFilter) out.push(`\t\tsearch_group_filter "${p.searchGroupFilter}"`);
  for (const [dn, roles] of Object.entries(p.groupRoleMap)) {
    out.push(`\t\tgroups {`, `\t\t\t"${dn}" ${roles.join(" ")}`, `\t\t}`);
  }
  out.push(`\t}`);
  return out;
}

function renderOidc(p: Extract<EdgeIdentityProvider, { type: "oidc" }>): string[] {
  return [
    `\toauth identity provider generic ${p.realm} {`,
    `\t\trealm ${p.realm}`,
    `\t\tbase_auth_url ${p.issuerUrl}`,
    `\t\tmetadata_url ${p.issuerUrl.replace(/\/+$/, "")}/.well-known/openid-configuration`,
    `\t\tclient_id ${p.clientId}`,
    `\t\tclient_secret "{env.${edgeSecretEnvVar(p) ?? ""}}"`,
    `\t\tscopes ${p.scopes.join(" ")}`,
    `\t\tuser_group_filters ${p.groupsClaim}`,
    `\t}`,
  ];
}

/**
 * Render the whole `security { ... }` block.
 *
 * ⚠️ Provider order is preserved verbatim. Caddy Security evaluates providers in the order
 * declared, so reordering here would silently change which realm authenticates a user.
 */
export function renderEdgeSecurityBlock(config: EdgeIdentityConfig): string {
  const lines: string[] = [
    "# Generated by AppBay — do not edit manually",
    "security {",
  ];

  for (const p of config.providers) {
    if (p.type === "local") lines.push(...renderLocal(p));
    else if (p.type === "ldap") lines.push(...renderLdap(p));
    else lines.push(...renderOidc(p));
  }

  const primary = config.providers[0];
  lines.push(
    `\tauthentication portal appbay {`,
    `\t\tcrypto default token lifetime 3600`,
    `\t\tenable identity store ${primary?.realm ?? "local"}`,
    `\t\tcookie insecure off`,
    `\t\ttransform user {`,
    `\t\t\tmatch origin local`,
    `\t\t\taction add role authp/user`,
    `\t\t}`,
    `\t}`,
    "}",
    "",
  );
  return lines.join("\n");
}

/**
 * Environment entries the edge container needs so `{env.…}` placeholders resolve.
 *
 * Returned as reference URIs — the caller resolves them through the normal secret path so
 * edge credentials travel exactly like every other secret, with no second mechanism.
 */
export function edgeSecretEnvMapping(config: EdgeIdentityConfig): Array<{ envVar: string; ref: string }> {
  const out: Array<{ envVar: string; ref: string }> = [];
  for (const p of config.providers) {
    // ⚠️ Narrow on `type`, not on "did edgeSecretEnvVar return something". Inferring the
    // provider shape from a helper's truthiness is an undocumented contract: add a
    // fourth provider that needs no secret and this silently reads the wrong field.
    if (p.type === "local") continue;
    const envVar = edgeSecretEnvVar(p);
    if (!envVar) continue;
    out.push({ envVar, ref: p.type === "ldap" ? p.bindPasswordRef : p.clientSecretRef });
  }
  return out;
}
