// Generated by work-graph.py. The claim and provenance layers are fixed;
// the domain layer comes from the project's own module.

CREATE NODE TABLE IF NOT EXISTS `Question`(`id` STRING, `text` STRING, `status` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Hypothesis`(`id` STRING, `text` STRING, `status` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Finding`(`id` STRING, `text` STRING, `standing` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `ProbeRecord`(`id` STRING, `type` STRING, `timestamp` STRING, `verdict` STRING, `key_evidence` STRING, `command` STRING, `exit_code` INT64, `output_kind` STRING, `file` STRING, `run` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Cohort`(`id` STRING, `definition` STRING, `n` INT64, `source` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Judgement`(`id` STRING, `at` STRING, `who` STRING, `what` STRING, `chose` STRING, `instead_of` STRING, `why` STRING, `evidence` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Run`(`id` STRING, `config` STRING, `code_version` STRING, `data_epoch` STRING, `metrics` STRING, `path` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Code`(`id` STRING, `path` STRING, `sha256` STRING, `stored` STRING, `version` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Artifact`(`id` STRING, `path` STRING, `bytes` INT64, `sha256` STRING, `run` STRING, PRIMARY KEY (`id`));
CREATE NODE TABLE IF NOT EXISTS `Product`(`name` STRING, `commit` STRING, `snapshot_date` STRING, `role` STRING, PRIMARY KEY (`name`));   // domain
CREATE NODE TABLE IF NOT EXISTS `CodeSite`(`site` STRING, `product` STRING, `path` STRING, `line` STRING, `symbol` STRING, `kind` STRING, PRIMARY KEY (`site`));   // domain
CREATE NODE TABLE IF NOT EXISTS `Gap`(`gap_id` STRING, `title` STRING, `decision` STRING, `spec` STRING, PRIMARY KEY (`gap_id`));   // domain

// `RAISES` has no rows in this corpus: (:Question)-[:RAISES]->(:?)
CREATE REL TABLE IF NOT EXISTS `BEARS_ON`(FROM `ProbeRecord` TO `Hypothesis`);
// `ANSWERS` has no rows in this corpus: (:ProbeRecord)-[:ANSWERS]->(:?)
CREATE REL TABLE IF NOT EXISTS `CITES`(FROM `Finding` TO `ProbeRecord`);
// `REFERS_TO` has no rows in this corpus: (:ProbeRecord)-[:REFERS_TO]->(:?)
CREATE REL TABLE IF NOT EXISTS `MOVED_BY`(FROM `Hypothesis` TO `Finding`);
// `OVER` has no rows in this corpus: (:ProbeRecord)-[:OVER]->(:?)
// `SUPERSEDES` has no rows in this corpus: (:Finding)-[:SUPERSEDES]->(:?)
// `REFINES` has no rows in this corpus: (:Finding)-[:REFINES]->(:?)
// `NARROWS` has no rows in this corpus: (:Finding)-[:NARROWS]->(:?)
// `EXTENDS` has no rows in this corpus: (:Finding)-[:EXTENDS]->(:?)
// `OVERTAKEN_BY` has no rows in this corpus: (:Finding)-[:OVERTAKEN_BY]->(:?)
// `INVALIDATES` has no rows in this corpus: (:ProbeRecord)-[:INVALIDATES]->(:?)
// `JUDGED` has no rows in this corpus: (:Judgement)-[:JUDGED]->(:?)
CREATE REL TABLE IF NOT EXISTS `BECAUSE`(FROM `Judgement` TO `Finding`);
CREATE REL TABLE IF NOT EXISTS `RAN`(FROM `ProbeRecord` TO `Code`);
CREATE REL TABLE IF NOT EXISTS `PRODUCED`(FROM `ProbeRecord` TO `Artifact`);
CREATE REL TABLE IF NOT EXISTS `IN_RUN`(FROM `ProbeRecord` TO `Run`);
CREATE REL TABLE IF NOT EXISTS `USED_CODE`(FROM `Run` TO `Code`);
CREATE REL TABLE IF NOT EXISTS `WROTE`(FROM `Run` TO `Artifact`);
CREATE REL TABLE IF NOT EXISTS `ABOUT`(FROM `Finding` TO `CodeSite`);   // bridge
CREATE REL TABLE IF NOT EXISTS `DERIVES`(FROM `ProbeRecord` TO `CodeSite`);   // bridge
CREATE REL TABLE IF NOT EXISTS `INCLUDES`(FROM `Cohort` TO `CodeSite`);   // bridge
