/**
 * The two files that let a non-root service account reach ROOTFUL podman — RFC-001 S34.
 *
 * ⭐ WHY TWO FILES AND NOT ONE `setfacl`. The obvious move — `setfacl -m u:appbay:rw
 * /run/podman/podman.sock` — works exactly once. systemd recreates the socket on every start of
 * `podman.socket`, and the ACL was on the old inode. Both files here are declarations systemd
 * re-applies itself, so the grant survives a socket restart and a reboot.
 *
 * ⭐ WHY THE DIRECTORY NEEDS ITS OWN FILE. `SocketGroup=` grants the socket. It does not grant
 * the path to it: `/run/podman` is created `0700 root root` by podman's own
 * `/usr/lib/tmpfiles.d/podman.conf`, so the account gets `connect: permission denied` on a
 * socket whose mode is already correct. `DirectoryMode=` in the socket unit does not help —
 * it applies only when systemd creates the parent, and tmpfiles created it first. Measured in
 * probe-89.
 *
 * ⚠️ Neither file is the whole grant. Without `CONTAINER_HOST` in the control plane's
 * environment, podman run by a non-root user goes ROOTLESS and never touches this socket — see
 * `podmanRootfulEnv` in `@appbay/core`, which the systemd unit and the doctor probe both use.
 */

import { PODMAN_ROOTFUL_SOCKET_DIR } from "@appbay/core";

export { PODMAN_ROOTFUL_SOCKET_DIR };

/** Drop-in directory for the podman socket unit. */
export const PODMAN_SOCKET_DROPIN_DIR = "/etc/systemd/system/podman.socket.d";

/** The drop-in itself. `10-` leaves room for an operator's own overrides above and below. */
export const PODMAN_SOCKET_DROPIN = `${PODMAN_SOCKET_DROPIN_DIR}/10-appbay.conf`;

/**
 * The tmpfiles override.
 *
 * ⚠️ THE BASENAME IS LOAD-BEARING and must not be `podman.conf`. systemd-tmpfiles takes at most
 * one file per basename across its search path, with /etc winning — so `/etc/tmpfiles.d/podman.conf`
 * would SHADOW `/usr/lib/tmpfiles.d/podman.conf` and silently drop its other lines (the
 * `/tmp/podman-run-*` and `/var/tmp/container_images*` cleanup). `zz-` sorts after it, so the
 * `z` line below is applied on top of podman's own `D! /run/podman 0700 root root` rather than
 * replacing it. Verified across a reboot in probe-89.
 */
export const PODMAN_TMPFILES_OVERRIDE = "/etc/tmpfiles.d/zz-appbay-podman.conf";

/** `SocketGroup=` on podman.socket, so the socket is created group-owned by the service account. */
export function renderPodmanSocketDropin(serviceUser: string): string {
  return [
    "# Generated by `appbay init-system` — do not edit manually.",
    "#",
    "# Makes the rootful Podman API socket group-readable by the account the control plane",
    "# runs as. This is the same privilege class the Docker path grants with",
    "# `usermod -aG docker`: root-equivalent control of this host's containers.",
    "",
    "[Socket]",
    `SocketGroup=${serviceUser}`,
    // Fedora's own unit already sets this; restating it means the drop-in does not depend on
    // a default that a distro or a future podman release could change underneath it.
    "SocketMode=0660",
    "",
  ].join("\n");
}

/** `z` line adjusting /run/podman so the service account can traverse into it. */
export function renderPodmanTmpfilesOverride(serviceUser: string): string {
  return [
    "# Generated by `appbay init-system` — do not edit manually.",
    "#",
    `# podman's own tmpfiles creates ${PODMAN_ROOTFUL_SOCKET_DIR} as 0700 root root, which the`,
    "# service account cannot traverse — so SocketGroup= on podman.socket grants a socket that",
    "# is still unreachable. `z` adjusts an existing path; this file sorts after podman.conf.",
    "#",
    "# 0750: the group may enter, everyone else is unchanged from podman's own intent.",
    `z ${PODMAN_ROOTFUL_SOCKET_DIR} 0750 root ${serviceUser} -`,
    "",
  ].join("\n");
}
