/**
 * The systemd unit for the AppBay control plane — RFC-001 S33.
 *
 * ⭐ WHY THIS EXISTS, AND WHAT IT IS NOT FOR. RFC-001 2.7 proposed this unit as the
 * prerequisite for deleting `/etc/appbay/config`. It is not: a unit's `Environment=` reaches the
 * processes systemd starts and nothing else, while tier 2 answers "where does appbay live" for
 * an operator typing a command — measured in probe-86, where deleting the file made the CLI
 * resolve a personal `~/.config` path over a service install.
 *
 * The unit is worth shipping on its own merits. Without it the control plane only runs while
 * somebody has run `appbay server start` by hand, and does not come back after a reboot.
 *
 * ⚠️ `Environment=APPBAY_HOME=` IS STILL LOAD-BEARING HERE, for a different reason than the RFC
 * gave. systemd starts services with a nearly empty environment — no login shell, no profile —
 * so without it the unit would resolve the home from tier 2, or fall through to `~/.appbay` of
 * whatever user it runs as. Stating it makes the unit independent of the tiers below.
 */

/** Where the unit is installed. */
export const SERVER_UNIT_NAME = "appbay-server.service";
export const SERVER_UNIT_PATH = `/etc/systemd/system/${SERVER_UNIT_NAME}`;

export interface ServerUnitOptions {
  /** Absolute path to the appbay binary — the unit cannot rely on PATH. */
  binaryPath: string;
  /** The APPBAY_HOME this host is bound to. */
  home: string;
  /** Container runtime unit to order after: `docker.service` or `podman.socket`. */
  runtimeUnit: string;
  /** User to run as. Omitted for an operator install, where the invoking user owns the tree. */
  user?: string;
}

/**
 * Render the unit.
 *
 * `Type=oneshot` with `RemainAfterExit=yes` because `appbay server start` brings the compose
 * stack up and exits — it is not itself the long-running process. A `Type=simple` unit would
 * consider the service dead the moment the command returned and restart it forever.
 */
export function renderServerUnit(options: ServerUnitOptions): string {
  const { binaryPath, home, runtimeUnit, user } = options;
  return [
    "# Generated by `appbay init-system` — do not edit manually.",
    "#",
    "# ⚠️ This unit does NOT make /etc/appbay/config removable. Its Environment= reaches the",
    "# processes systemd starts; an operator's shell never sees it. See probe-86.",
    "",
    "[Unit]",
    "Description=AppBay control plane",
    "Documentation=https://github.com/kundeng/appbay",
    // The compose stack cannot come up before the runtime's socket exists. Ordering only —
    // `Requires=` would take the control plane down with the runtime on every restart.
    `After=network-online.target ${runtimeUnit}`,
    `Wants=network-online.target ${runtimeUnit}`,
    "",
    "[Service]",
    // `appbay server start` returns once the stack is healthy; it is not the service process.
    "Type=oneshot",
    "RemainAfterExit=yes",
    `Environment=APPBAY_HOME=${home}`,
    ...(user ? [`User=${user}`] : []),
    `ExecStart=${binaryPath} server start`,
    `ExecStop=${binaryPath} server stop`,
    // The health wait inside `server start` can legitimately take a while on a cold image pull.
    "TimeoutStartSec=300",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}
