/**
 * Compose renderer -- assembles the final Docker Compose YAML from all
 * pipeline stages: base compose + overlay fragments + trait modifications +
 * static overrides.
 *
 * Merge order (later overrides earlier):
 *   1. Base compose (from upstream transform or raw)
 *   2. Overlay fragments (from active overlays)
 *   3. Trait modifications (from trait engine)
 *   4. Static overrides (from appbay.yaml `overrides:` section)
 *
 * Merge rules (same as overlay engine):
 *   - `environment`, `volumes`, `ports` arrays: append
 *   - `labels`, `depends_on` objects: shallow merge
 *   - Scalars: override
 *
 * See design.md "Compose Renderer" and agents.md for canonical reference.
 */

import { stringify, parse } from "yaml";

// ---------------------------------------------------------------------------
// Header comment prepended to every rendered compose file
// ---------------------------------------------------------------------------

const HEADER_COMMENT = "# Generated by Appbay — do not edit manually\n";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Input to the compose renderer. */
export interface RenderInput {
  /** App name (directory name). */
  appName: string;
  /** Base compose document (after upstream transform if applicable, or raw). */
  compose: Record<string, unknown>;
  /** Static overrides from appbay.yaml `overrides:` section, keyed by service name. */
  overrides?: Record<string, Record<string, unknown>>;
  /** Merged overlay fragments from active overlays, keyed by service name. */
  overlayServices?: Record<string, Record<string, unknown>>;
  /** Compose modifications from trait engine. */
  traitCompose?: Record<string, unknown>;
  /** Auxiliary files generated by trait transforms. */
  auxiliaryFiles?: Array<{ path: string; content: string }>;
}

/** Output from the compose renderer. */
export interface RenderOutput {
  /** Rendered compose as a YAML string (with header comment). */
  compose: string;
  /** Rendered compose as an object (for diff / inspection). */
  composeObject: Record<string, unknown>;
  /** All auxiliary files to write alongside the compose file. */
  auxiliaryFiles: Array<{ path: string; content: string }>;
}

// ---------------------------------------------------------------------------
// Merge helpers (shared rules with overlay engine)
// ---------------------------------------------------------------------------

/** Keys whose values are arrays and should be merged by appending. */
const APPEND_ARRAY_KEYS = new Set(["environment", "volumes", "ports"]);

/** Keys whose values are objects and should be shallow-merged. */
const MERGE_OBJECT_KEYS = new Set(["labels", "depends_on"]);

/**
 * Returns `true` when `v` is a plain object (not an array, null, or other
 * non-record type).
 */
export function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Deep-merge a fragment into a base service definition following Appbay
 * merge rules.
 */
export function mergeServiceFragment(
  base: Record<string, unknown>,
  fragment: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...base };

  for (const [key, fragmentValue] of Object.entries(fragment)) {
    const baseValue = result[key];

    if (APPEND_ARRAY_KEYS.has(key)) {
      const baseArr = Array.isArray(baseValue) ? baseValue : [];
      const fragArr = Array.isArray(fragmentValue) ? fragmentValue : [];
      result[key] = [...baseArr, ...fragArr];
    } else if (MERGE_OBJECT_KEYS.has(key)) {
      const baseObj = isPlainObject(baseValue) ? baseValue : {};
      const fragObj = isPlainObject(fragmentValue) ? fragmentValue : {};
      result[key] = { ...baseObj, ...fragObj };
    } else if (isPlainObject(baseValue) && isPlainObject(fragmentValue)) {
      result[key] = mergeServiceFragment(baseValue, fragmentValue);
    } else {
      result[key] = fragmentValue;
    }
  }

  return result;
}

/**
 * Merge a set of per-service fragments into the compose document's services
 * block.  Missing services are created; existing services are deep-merged.
 */
export function mergeServicesInto(
  compose: Record<string, unknown>,
  serviceFragments: Record<string, Record<string, unknown>>,
): Record<string, unknown> {
  const services = isPlainObject(compose.services)
    ? { ...(compose.services as Record<string, Record<string, unknown>>) }
    : {};

  for (const [svcName, fragment] of Object.entries(serviceFragments)) {
    // Skip empty fragments to avoid corrupting the compose
    if (!isPlainObject(fragment) || Object.keys(fragment).length === 0) {
      continue;
    }

    if (isPlainObject(services[svcName])) {
      services[svcName] = mergeServiceFragment(
        services[svcName] as Record<string, unknown>,
        fragment,
      );
    } else {
      services[svcName] = { ...fragment };
    }
  }

  return { ...compose, services };
}

/**
 * Merge a full compose object (e.g., from trait engine) into the base compose.
 * Top-level keys like `services`, `networks`, `volumes` are each merged
 * according to their semantics.
 */
export function mergeComposeObjects(
  base: Record<string, unknown>,
  overlay: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...base };

  for (const [key, overlayValue] of Object.entries(overlay)) {
    const baseValue = result[key];

    if (key === "services") {
      // Services are merged at the per-service level.
      const baseSvcs = isPlainObject(baseValue) ? baseValue : {};
      const overlaySvcs = isPlainObject(overlayValue) ? overlayValue : {};
      const merged = { ...baseSvcs };

      for (const [svcName, svcDef] of Object.entries(overlaySvcs)) {
        if (isPlainObject(merged[svcName]) && isPlainObject(svcDef)) {
          merged[svcName] = mergeServiceFragment(
            merged[svcName] as Record<string, unknown>,
            svcDef as Record<string, unknown>,
          );
        } else {
          merged[svcName] = svcDef;
        }
      }

      result[key] = merged;
    } else if (isPlainObject(baseValue) && isPlainObject(overlayValue)) {
      // Other top-level objects (networks, volumes, etc.) shallow-merge.
      result[key] = { ...baseValue, ...overlayValue };
    } else {
      result[key] = overlayValue;
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// Main render function
// ---------------------------------------------------------------------------

/**
 * Render the final Docker Compose YAML from all pipeline stages.
 *
 * This is a pure function -- it does not read or write the filesystem.
 */
export function renderCompose(input: RenderInput): RenderOutput {
  const {
    compose: baseCompose,
    overrides,
    overlayServices,
    traitCompose,
    auxiliaryFiles = [],
  } = input;

  // Start with a shallow copy of the base compose.
  let composed: Record<string, unknown> = { ...baseCompose };

  // 1. Base compose is already `composed`.

  // 2. Overlay fragments (from active overlays).
  if (overlayServices && Object.keys(overlayServices).length > 0) {
    composed = mergeServicesInto(composed, overlayServices);
  }

  // 3. Trait modifications (full compose object from trait engine).
  if (traitCompose && Object.keys(traitCompose).length > 0) {
    composed = mergeComposeObjects(composed, traitCompose);
  }

  // 4. Static overrides (from appbay.yaml `overrides:` section).
  if (overrides && Object.keys(overrides).length > 0) {
    composed = mergeServicesInto(composed, overrides);
  }

  // Stringify to YAML with header comment.
  const yamlBody = stringify(composed, {
    lineWidth: 0, // Avoid line wrapping
  });
  const yamlOutput = HEADER_COMMENT + yamlBody;

  return {
    compose: yamlOutput,
    composeObject: composed,
    auxiliaryFiles: [...auxiliaryFiles],
  };
}
