/**
 * Trait application engine.
 *
 * Takes an app's trait declarations (from appbay.yaml), validates them
 * against the registry, checks for conflicts, and applies each trait's
 * transform in declaration order.
 *
 * OAM rules enforced:
 *  1. Traits applied in declaration order.
 *  2. One configuration per trait type per service.
 *  3. Check conflictsWith before applying.
 *  4. Validate trait properties against the trait's Zod schema.
 *  5. App-level traits apply to the whole app (no service param).
 *  6. Service-level traits apply to a specific service.
 *  7. Unknown trait type produces an error.
 *  8. Schema validation failure produces an error with Zod details.
 */

import type { TraitRegistry } from "../traits/registry.js";
import type { CompilerContext, TraitTransformInput } from "../traits/types.js";

// ---------------------------------------------------------------------------
// Input / Output Types
// ---------------------------------------------------------------------------

/** Input to the trait application engine. */
export interface TraitEngineInput {
  /** App name. */
  appName: string;
  /** Current compose state (mutable -- traits may modify it). */
  compose: Record<string, unknown>;
  /** App-level traits declared in the top-level `traits` array. */
  appTraits: Array<{ type: string; [key: string]: unknown }>;
  /** Per-service traits declared in `services.<name>.traits`. */
  serviceTraits: Record<
    string,
    Array<{ type: string; [key: string]: unknown }>
  >;
  /** The trait registry containing all registered trait definitions. */
  registry: TraitRegistry;
  /** Compiler context with project/environment/runtime info. */
  context: CompilerContext;
}

/** Output from the trait application engine. */
export interface TraitEngineOutput {
  /** Compose state after all traits have been applied. */
  compose: Record<string, unknown>;
  /** Auxiliary files generated by trait transforms (e.g., Traefik configs). */
  auxiliaryFiles: Array<{ path: string; content: string }>;
  /**
   * Metadata emitted by trait transforms for out-of-band consumers.
   * Keyed by trait type — last writer wins per key if the same trait type
   * appears multiple times (which is prevented by the duplicate-type check).
   *
   * Example: the backup trait emits `{ backup: { schedule, retention, volumes } }`
   * for the job queue scheduler to pick up at runtime.
   */
  traitMetadata: Record<string, Record<string, unknown>>;
  /** Errors encountered during trait application. */
  errors: TraitError[];
  /** Warnings encountered during trait application. */
  warnings: TraitWarning[];
  /** Shepherd actions collected from all traits (operational lifecycle tasks). */
  shepherdActions: import("../traits/types.js").ShepherdAction[];
}

/** An error produced during trait application. */
export interface TraitError {
  /** The trait type that caused the error. */
  trait: string;
  /** The service name (if service-scoped). */
  service?: string;
  /** Human-readable error message. */
  message: string;
  /** Additional details (e.g., Zod validation issues). */
  details?: unknown;
}

/** A warning produced during trait application. */
export interface TraitWarning {
  /** The trait type that caused the warning. */
  trait: string;
  /** The service name (if service-scoped). */
  service?: string;
  /** Human-readable warning message. */
  message: string;
}

// ---------------------------------------------------------------------------
// Engine Implementation
// ---------------------------------------------------------------------------

/**
 * Apply all traits (app-level and service-level) to a compose state.
 *
 * Processing order:
 *  1. App-level traits in declaration order.
 *  2. Service-level traits for each service, in declaration order per service.
 *     Services are processed in the order they appear in `serviceTraits`.
 *
 * If any errors are encountered (unknown trait, duplicate, conflict, schema
 * validation failure), the error is recorded and the offending trait is
 * skipped. Processing continues with the remaining traits so that all errors
 * are surfaced in a single pass.
 */
export function applyTraits(input: TraitEngineInput): TraitEngineOutput {
  const { appName, registry, context } = input;
  let compose = { ...input.compose };
  const auxiliaryFiles: Array<{ path: string; content: string }> = [];
  const traitMetadata: Record<string, Record<string, unknown>> = {};
  const errors: TraitError[] = [];
  const warnings: TraitWarning[] = [];
  const shepherdActions: import("../traits/types.js").ShepherdAction[] = [];

  // --- App-level traits ---
  const appTraitTypesSeen = new Set<string>();

  // Every trait declared on this app, app-level and service-level, in declaration
  // order. Passed to each transform as `siblingTraits` (minus itself) so traits that
  // must AGREE on a value can read it from its owner instead of guessing.
  //
  // ⚠️ Built from DECLARED config, before each trait's own Zod parse and before any
  // transform runs. That is deliberate: it makes sibling access independent of trait
  // ordering, so there is no cycle and no "did the other trait run yet" question.
  const allDeclaredTraits: Array<{ type: string; [key: string]: unknown }> = [
    ...input.appTraits,
    ...Object.values(input.serviceTraits).flat(),
  ];
  const siblingsOf = (self: { type: string; [key: string]: unknown }) =>
    allDeclaredTraits.filter((t) => t !== self);

  for (const traitConfig of input.appTraits) {
    // Extract `service` from raw config before Zod strips it.
    // App-level traits may declare `service: <name>` to target a specific
    // compose service (e.g. `type: gpu; service: ollama`). This field is not
    // part of the individual trait schemas so Zod would discard it, but we
    // preserve it here to route service-scoped traits correctly.
    const serviceFromConfig = (
      traitConfig as { service?: string }
    ).service;
    const { type, ...rest } = traitConfig;

    // Rule 7: unknown trait type
    const definition = registry.get(type);
    if (!definition) {
      errors.push({
        trait: type,
        message: `Unknown trait type "${type}". This trait is not registered.`,
      });
      continue;
    }

    // Rule 2: one configuration per trait type (app scope)
    if (appTraitTypesSeen.has(type)) {
      errors.push({
        trait: type,
        message:
          `Duplicate trait type "${type}" at app scope. ` +
          "OAM rule: one configuration per trait type per scope.",
      });
      continue;
    }

    // Rule 3: check conflictsWith against already-applied app traits
    const conflictFound = checkConflicts(
      type,
      definition.conflictsWith,
      appTraitTypesSeen,
    );
    if (conflictFound) {
      errors.push({
        trait: type,
        message: conflictFound,
      });
      continue;
    }

    // Rule 8: validate properties against Zod schema
    const parseResult = definition.schema.safeParse(traitConfig);
    if (!parseResult.success) {
      errors.push({
        trait: type,
        message: `Schema validation failed for trait "${type}".`,
        details: parseResult.error.issues,
      });
      continue;
    }

    // Rule 5: app-level traits may optionally declare a target service via the
    // `service` field in the raw YAML config (service-scoped traits like gpu
    // require this; app-scoped traits ignore it).
    //
    // 🚨 A NAMED SERVICE THAT DOES NOT EXIST USED TO COMPILE CLEAN. `service: NOPE` on an
    // ingress trait produced "1 compiled, 0 error(s)" and no route — the trait applied
    // itself to nothing and said nothing. A typo in one word silently cost the app its
    // only way in, which is the worst possible ratio of cause to consequence.
    //
    // ⚠️ Checked HERE, once, rather than in each trait: every trait that accepts `service`
    // has the same failure, and a per-trait check is one more thing to forget when the
    // next trait is written.
    if (serviceFromConfig !== undefined) {
      const services = (compose.services ?? {}) as Record<string, unknown>;
      if (!Object.prototype.hasOwnProperty.call(services, serviceFromConfig)) {
        const known = Object.keys(services);
        errors.push({
          trait: type,
          service: serviceFromConfig,
          message:
            `Trait "${type}" targets service "${serviceFromConfig}", which this app does ` +
            `not define. ` +
            (known.length > 0
              ? `Known services: ${known.join(", ")}.`
              : "This app's compose declares no services."),
        });
        continue;
      }
    }

    appTraitTypesSeen.add(type);

    const transformInput: TraitTransformInput = {
      app: appName,
      service: serviceFromConfig,
      properties: parseResult.data,
      compose,
      context,
      siblingTraits: siblingsOf(traitConfig),
    };

    const output = definition.transform(transformInput);
    compose = output.compose;
    if (output.auxiliaryFiles) {
      auxiliaryFiles.push(...output.auxiliaryFiles);
    }
    if (output.metadata) {
      Object.assign(traitMetadata, output.metadata);
    }
    if (output.shepherd) {
      shepherdActions.push(...output.shepherd);
    }
    if (output.errors) {
      for (const message of output.errors) errors.push({ trait: type, message });
    }
  }

  // --- Service-level traits ---
  for (const [serviceName, traits] of Object.entries(input.serviceTraits)) {
    const serviceTraitTypesSeen = new Set<string>();

    for (const traitConfig of traits) {
      const { type, ...rest } = traitConfig;

      // Rule 7: unknown trait type
      const definition = registry.get(type);
      if (!definition) {
        errors.push({
          trait: type,
          service: serviceName,
          message: `Unknown trait type "${type}". This trait is not registered.`,
        });
        continue;
      }

      // Rule 2: one configuration per trait type per service
      if (serviceTraitTypesSeen.has(type)) {
        errors.push({
          trait: type,
          service: serviceName,
          message:
            `Duplicate trait type "${type}" on service "${serviceName}". ` +
            "OAM rule: one configuration per trait type per service.",
        });
        continue;
      }

      // Rule 3: check conflictsWith against already-applied service traits
      const conflictFound = checkConflicts(
        type,
        definition.conflictsWith,
        serviceTraitTypesSeen,
      );
      if (conflictFound) {
        errors.push({
          trait: type,
          service: serviceName,
          message: conflictFound,
        });
        continue;
      }

      // Rule 8: validate properties against Zod schema
      const parseResult = definition.schema.safeParse(traitConfig);
      if (!parseResult.success) {
        errors.push({
          trait: type,
          service: serviceName,
          message: `Schema validation failed for trait "${type}" on service "${serviceName}".`,
          details: parseResult.error.issues,
        });
        continue;
      }

      // Rule 6: service-level traits include the service name
      serviceTraitTypesSeen.add(type);

      const transformInput: TraitTransformInput = {
        app: appName,
        service: serviceName,
        properties: parseResult.data,
        compose,
        context,
        siblingTraits: siblingsOf(traitConfig),
      };

      const output = definition.transform(transformInput);
      compose = output.compose;
      if (output.auxiliaryFiles) {
        auxiliaryFiles.push(...output.auxiliaryFiles);
      }
      if (output.metadata) {
        Object.assign(traitMetadata, output.metadata);
      }
      if (output.shepherd) {
        shepherdActions.push(...output.shepherd);
      }
      if (output.errors) {
        for (const message of output.errors) {
          errors.push({ trait: type, service: serviceName, message });
        }
      }
    }
  }

  return { compose, auxiliaryFiles, traitMetadata, errors, warnings, shepherdActions };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Check if a trait type conflicts with any already-applied trait types.
 * Returns a conflict error message if found, or null if no conflict.
 */
function checkConflicts(
  traitType: string,
  conflictsWith: string[],
  appliedTypes: Set<string>,
): string | null {
  for (const conflicting of conflictsWith) {
    if (appliedTypes.has(conflicting)) {
      return (
        `Trait "${traitType}" conflicts with "${conflicting}". ` +
        "These traits cannot be applied to the same scope."
      );
    }
  }
  return null;
}
