/**
 * Tests for the instance config schema ($APPBAY_HOME/project.yaml).
 *
 * The behaviour that matters here is what happens to BAD input, because the
 * file this parses was previously read by regex — which cannot distinguish a
 * missing key from a malformed one and silently yields undefined for both.
 */

import { describe, it, expect } from "vitest";
import {
  parseInstanceConfig,
  InstanceConfigSchema,
  ContainerRuntimeSchema,
  DEFAULT_CONTAINER_RUNTIME,
} from "../instance.js";

describe("parseInstanceConfig", () => {
  it("reads the keys appbay init writes", () => {
    const cfg = parseInstanceConfig(
      `# Appbay project configuration — generated by "appbay init"\nproject: homelab\ndomain: example.com\n`,
    );
    expect(cfg.project).toBe("homelab");
    expect(cfg.domain).toBe("example.com");
    expect(cfg.container_runtime).toBeUndefined();
  });

  it("reads container_runtime when present", () => {
    expect(parseInstanceConfig("container_runtime: podman\n").container_runtime).toBe("podman");
    expect(parseInstanceConfig("container_runtime: docker\n").container_runtime).toBe("docker");
  });

  it("returns empty for empty, comment-only and non-mapping input", () => {
    expect(parseInstanceConfig("")).toEqual({});
    expect(parseInstanceConfig("# nothing but a comment\n")).toEqual({});
    expect(parseInstanceConfig("just a bare string\n")).toEqual({});
    expect(parseInstanceConfig("- a\n- list\n")).toEqual({});
  });

  it("returns empty rather than throwing on malformed YAML", () => {
    // A corrupt project.yaml must not take down `appbay --help`.
    expect(parseInstanceConfig("project: [unclosed\n\tbad: indent\n")).toEqual({});
  });

  it("drops unknown keys instead of rejecting the file", () => {
    // Forward compatibility: a newer appbay writing a key this version does not
    // know must not break this version.
    const cfg = parseInstanceConfig("project: p\nsome_future_key: 42\n");
    expect(cfg.project).toBe("p");
    expect(cfg).not.toHaveProperty("some_future_key");
  });

  it("rejects an unknown container_runtime value", () => {
    expect(ContainerRuntimeSchema.safeParse("rkt").success).toBe(false);
    expect(ContainerRuntimeSchema.safeParse("podman").success).toBe(true);
    // The whole-object parse fails closed, so the caller gets {} and falls back
    // to the default rather than spawning an unvetted binary.
    expect(parseInstanceConfig("container_runtime: rkt\n")).toEqual({});
  });

  it("treats every key as optional", () => {
    expect(InstanceConfigSchema.safeParse({}).success).toBe(true);
  });

  it("defaults to docker", () => {
    expect(DEFAULT_CONTAINER_RUNTIME).toBe("docker");
  });
});
