import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { join } from "node:path";
import { mkdtemp, mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { compile, whenClauseLabel } from "../compile.js";
import type { CompileOptions } from "../compile.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Create a temporary directory structure for compile tests.
 * Returns a base path containing apps/, renders/, and state/ subdirs.
 */
async function createTempFixture(): Promise<string> {
  const base = await mkdtemp(join(tmpdir(), "appbay-compile-test-"));
  await mkdir(join(base, "apps"), { recursive: true });
  await mkdir(join(base, "renders"), { recursive: true });
  await mkdir(join(base, "state"), { recursive: true });
  return base;
}

/** Write a simple compose file for a named app. */
async function writeApp(
  base: string,
  appName: string,
  compose: string,
  appbayYaml?: string,
): Promise<void> {
  const appDir = join(base, "apps", appName);
  await mkdir(appDir, { recursive: true });
  await writeFile(join(appDir, "docker-compose.yml"), compose, "utf-8");
  if (appbayYaml) {
    await writeFile(join(appDir, "appbay.yaml"), appbayYaml, "utf-8");
  }
}

const SIMPLE_COMPOSE = `services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
`;

const COMPOSE_WITH_SCOPED_VAR = `services:
  web:
    image: nginx:latest
    environment:
      - APP_DOMAIN=\${{project.DOMAIN}}
`;

const APPBAY_WITH_UPSTREAM = `project: homelab
environment: prod
shared_network:
  - appbay_shared
upstream:
  source: docker-compose.yml
  expose:
    - service: web
      networks:
        - appbay_shared
`;

const APPBAY_WITH_INGRESS = `project: homelab
environment: prod
services:
  web:
    traits:
      - type: ingress
        host: myapp.example.com
        port: 80
`;

const APPBAY_WITH_BACKUP = `traits:
  - type: backup
    schedule: "0 3 * * *"
    retention: 14
`;

const APPBAY_WITH_BACKUP_VOLUMES = `traits:
  - type: backup
    schedule: "0 4 * * *"
    retention: 30
    volumes:
      - myapp_data
      - myapp_db
`;

const APPBAY_WITH_OVERLAY_AND = `overlays:
  - when:
      - traefik
    services:
      web:
        labels:
          traefik.enable: "true"
`;

const APPBAY_WITH_OVERLAY_ANY = `overlays:
  - when:
      any:
        - traefik
        - caddy
    services:
      web:
        restart: unless-stopped
`;

const COMPOSE_WITH_MAGIC_VAR = `services:
  web:
    image: nginx:latest
    environment:
      - MY_ID=\${uuid}
      - PLAIN_ENTRY
      - PORT=8080
`;

const COMPOSE_WITH_UNRESOLVED_VAR = `services:
  web:
    image: nginx:latest
    environment:
      - APP_DOMAIN=\${{project.MISSING_KEY}}
`;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("compile()", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempFixture();
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  function makeOptions(overrides?: Partial<CompileOptions>): CompileOptions {
    return {
      appsDir: join(tempDir, "apps"),
      rendersDir: join(tempDir, "renders"),
      stateDir: join(tempDir, "state"),
      ...overrides,
    };
  }

  // -------------------------------------------------------------------------
  // 1. Compile discovers and processes a single app successfully
  // -------------------------------------------------------------------------

  it("discovers and processes a single app successfully", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.apps).toHaveLength(1);
    expect(result.apps[0]!.appName).toBe("myapp");
    expect(result.apps[0]!.rendered).toContain("nginx:latest");
    expect(result.apps[0]!.rendered).toContain("Generated by Appbay");
  });

  // -------------------------------------------------------------------------
  // 2. Compile returns 'new' plan status for first deploy
  // -------------------------------------------------------------------------

  it("returns 'new' plan status for first deploy", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.apps).toHaveLength(1);
    expect(result.apps[0]!.plan.status).toBe("new");
    expect(result.apps[0]!.plan.diff).not.toBeNull();
    // All diff lines should be adds for a new app.
    for (const line of result.apps[0]!.plan.diffLines) {
      expect(line.type).toBe("add");
    }
  });

  // -------------------------------------------------------------------------
  // 3. Compile with no apps found returns empty result
  // -------------------------------------------------------------------------

  it("returns empty result when no apps are found", async () => {
    // Empty apps directory -- no apps to discover.
    const result = await compile(makeOptions());

    expect(result.apps).toHaveLength(0);
  });

  // -------------------------------------------------------------------------
  // 4. Compile filters to specific apps when `apps` option is set
  // -------------------------------------------------------------------------

  it("filters to specific apps when apps option is set", async () => {
    await writeApp(tempDir, "app-a", SIMPLE_COMPOSE);
    await writeApp(
      tempDir,
      "app-b",
      SIMPLE_COMPOSE.replace("nginx", "httpd"),
    );
    await writeApp(
      tempDir,
      "app-c",
      SIMPLE_COMPOSE.replace("nginx", "caddy"),
    );

    const result = await compile(makeOptions({ apps: ["app-b"] }));

    expect(result.apps).toHaveLength(1);
    expect(result.apps[0]!.appName).toBe("app-b");
    expect(result.apps[0]!.rendered).toContain("httpd");
  });

  // -------------------------------------------------------------------------
  // 5. Compile collects discovery errors without stopping
  // -------------------------------------------------------------------------

  it("collects discovery errors without stopping other apps", async () => {
    // Valid app.
    await writeApp(tempDir, "good-app", SIMPLE_COMPOSE);

    // App with invalid appbay.yaml (bad YAML syntax).
    await writeApp(tempDir, "bad-app", SIMPLE_COMPOSE, "{{invalid yaml");

    const result = await compile(makeOptions());

    // Both apps should be processed (bad-app still has a valid compose).
    expect(result.apps).toHaveLength(2);
    const goodApp = result.apps.find((a) => a.appName === "good-app");
    const badApp = result.apps.find((a) => a.appName === "bad-app");
    expect(goodApp).toBeDefined();
    expect(badApp).toBeDefined();

    // There should be discovery errors for the bad-app.
    const discErrors = result.errors.filter(
      (e) => e.appName === "bad-app" && e.stage === "discover",
    );
    expect(discErrors.length).toBeGreaterThan(0);
  });

  // -------------------------------------------------------------------------
  // 6. Compile resolves scoped variables in compose
  // -------------------------------------------------------------------------

  it("resolves scoped variables in compose", async () => {
    await writeApp(tempDir, "myapp", COMPOSE_WITH_SCOPED_VAR);

    const result = await compile(
      makeOptions({
        projectVars: { DOMAIN: "example.com" },
      }),
    );

    expect(result.apps).toHaveLength(1);
    expect(result.apps[0]!.rendered).toContain("example.com");
    expect(result.apps[0]!.rendered).not.toContain("${{project.DOMAIN}}");
  });

  // -------------------------------------------------------------------------
  // 7. Compile handles app without appbay.yaml (pass-through)
  // -------------------------------------------------------------------------

  it("handles app without appbay.yaml as pass-through", async () => {
    // App with only a compose file, no appbay.yaml.
    await writeApp(tempDir, "simple-app", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.apps).toHaveLength(1);
    expect(result.apps[0]!.appName).toBe("simple-app");
    expect(result.apps[0]!.rendered).toContain("nginx:latest");
    // No errors related to missing appbay.yaml.
    const appErrors = result.errors.filter(
      (e) => e.appName === "simple-app",
    );
    expect(appErrors).toHaveLength(0);
  });

  // -------------------------------------------------------------------------
  // 8. traitMetadata flows end-to-end through the compile pipeline
  // -------------------------------------------------------------------------

  it("surfaces backup trait metadata in AppCompileResult.traitMetadata", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_BACKUP);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    expect(result.apps).toHaveLength(1);

    const app = result.apps[0]!;
    // The backup trait emits metadata keyed by "backup".
    expect(app.traitMetadata).toBeDefined();
    const backupMeta = app.traitMetadata["backup"] as Record<string, unknown>;
    expect(backupMeta).toBeDefined();
    expect(backupMeta.app).toBe("myapp");
    expect(backupMeta.schedule).toBe("0 3 * * *");
    expect(backupMeta.retention).toBe(14);
  });

  it("backup traitMetadata includes volumes when declared", async () => {
    await writeApp(
      tempDir,
      "dataapp",
      SIMPLE_COMPOSE,
      APPBAY_WITH_BACKUP_VOLUMES,
    );

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const app = result.apps[0]!;
    const backupMeta = app.traitMetadata["backup"] as Record<string, unknown>;
    expect(backupMeta.volumes).toEqual(["myapp_data", "myapp_db"]);
  });

  it("traitMetadata is empty for apps with no traits that emit metadata", async () => {
    // App with only ingress trait (no backup) — traitMetadata should be empty.
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_INGRESS);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const app = result.apps[0]!;
    expect(app.traitMetadata).toEqual({});
  });

  it("traitMetadata is empty for apps without appbay.yaml", async () => {
    await writeApp(tempDir, "plain-app", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const app = result.apps[0]!;
    expect(app.traitMetadata).toEqual({});
  });

  // -------------------------------------------------------------------------
  // 9. Scope resolver errors are reported at "resolve-variables" stage
  // -------------------------------------------------------------------------

  it("reports scope resolver errors when scoped var has no binding", async () => {
    await writeApp(tempDir, "myapp", COMPOSE_WITH_UNRESOLVED_VAR);

    const result = await compile(makeOptions()); // no projectVars

    const scopeErrors = result.errors.filter(
      (e) => e.stage === "resolve-variables",
    );
    expect(scopeErrors.length).toBeGreaterThan(0);
    expect(scopeErrors[0]!.appName).toBe("myapp");
  });

  // -------------------------------------------------------------------------
  // 10. Overlay activation — AND clause (array form)
  // -------------------------------------------------------------------------

  // ⚠️ These declare the peer app on disk rather than handing compile() a set. RFC-001 §5
  // made `when:` mean INSTALLED, and `compile()` derives that itself — so the only way to
  // say "traefik is installed" is for traefik to be installed. That is the point: the old
  // tests could assert an activation state the real system could not produce.

  it("activates AND overlay when all required apps are installed", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_OVERLAY_AND);
    await writeApp(tempDir, "traefik", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const app = result.apps.find((a) => a.appName === "myapp")!;
    expect(app.rendered).toContain("traefik.enable");
  });

  it("produces inactive-overlay warning when the required app is not installed", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_OVERLAY_AND);

    const result = await compile(makeOptions());

    const overlayWarnings = result.warnings.filter((w) =>
      w.includes("Overlay skipped"),
    );
    expect(overlayWarnings.length).toBeGreaterThan(0);
    expect(result.apps[0]!.rendered).not.toContain("traefik.enable");
  });

  it("evaluates `when:` against the FULL declared set, not the invocation's targets", async () => {
    // RFC-001 §5.2 — the property the old signature could not hold. `appbay up myapp` and
    // `appbay up` must produce the SAME artifact for myapp; previously the caller passed a
    // set derived from the target list, so narrowing the command line silently deactivated
    // overlays and re-rendered the app differently.
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_OVERLAY_AND);
    await writeApp(tempDir, "traefik", SIMPLE_COMPOSE);

    const all = await compile(makeOptions());
    const targeted = await compile(makeOptions({ apps: ["myapp"] }));

    expect(targeted.apps).toHaveLength(1);
    expect(targeted.apps[0]!.rendered).toContain("traefik.enable");
    expect(targeted.apps[0]!.rendered).toBe(
      all.apps.find((a) => a.appName === "myapp")!.rendered,
    );
  });

  // -------------------------------------------------------------------------
  // 11. Overlay activation — OR clause ({any} form)
  // -------------------------------------------------------------------------

  it("activates OR overlay when any required app is installed", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_OVERLAY_ANY);
    await writeApp(tempDir, "caddy", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    // ⚠️ Not apps[0]. compile() returns every discovered app sorted by name, and installing
    // the peer means the peer is compiled too — "caddy" sorts before "myapp".
    const app = result.apps.find((a) => a.appName === "myapp")!;
    expect(app.rendered).toContain("unless-stopped");
  });

  // -------------------------------------------------------------------------
  // 12. Magic var resolution (resolveMagicVars)
  // -------------------------------------------------------------------------

  it("resolves ${uuid} magic var in service environment", async () => {
    await writeApp(tempDir, "myapp", COMPOSE_WITH_MAGIC_VAR);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const rendered = result.apps[0]!.rendered;

    // ${uuid} should be replaced with a UUID-shaped string, not the literal pattern.
    expect(rendered).not.toContain("${uuid}");
    // UUID format check: 8-4-4-4-12 hex
    expect(rendered).toMatch(
      /MY_ID=[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
    );
  });

  it("passes through env entry with no '=' sign unchanged", async () => {
    await writeApp(tempDir, "myapp", COMPOSE_WITH_MAGIC_VAR);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    // PLAIN_ENTRY has no '=' — should appear verbatim in rendered output.
    expect(result.apps[0]!.rendered).toContain("PLAIN_ENTRY");
  });

  it("passes through env entry with literal value that is not a magic var", async () => {
    await writeApp(tempDir, "myapp", COMPOSE_WITH_MAGIC_VAR);

    const result = await compile(makeOptions());

    // PORT=8080 has '=' but parseMagicVar("8080") returns null → passes through.
    expect(result.apps[0]!.rendered).toContain("PORT=8080");
  });

  // -------------------------------------------------------------------------
  // 13. logicalChanges structure
  // -------------------------------------------------------------------------

  it("includes 'new' plan status in logicalChanges for first deploy", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE);

    const result = await compile(makeOptions());

    expect(result.apps[0]!.plan.status).toBe("new");
    // The app-level group should include the 'new' marker.
    const appGroup = result.apps[0]!.logicalChanges.find(
      (g) => g.svc === "",
    );
    expect(appGroup).toBeDefined();
    const newMarker = appGroup!.changes.find(
      (c) => c.op === "+" && c.type === "image",
    );
    expect(newMarker).toBeDefined();
    expect(newMarker!.text).toBe("myapp");
  });

  it("service-level trait appears in a service-keyed logicalChanges group", async () => {
    await writeApp(tempDir, "myapp", SIMPLE_COMPOSE, APPBAY_WITH_INGRESS);

    const result = await compile(makeOptions());

    expect(result.errors).toHaveLength(0);
    const svcGroup = result.apps[0]!.logicalChanges.find(
      (g) => g.svc === "web",
    );
    expect(svcGroup).toBeDefined();
    const ingressChange = svcGroup!.changes.find((c) => c.text === "ingress");
    expect(ingressChange).toBeDefined();
    expect(ingressChange!.op).toBe("+");
    expect(ingressChange!.type).toBe("trait");
  });
});

// ---------------------------------------------------------------------------
// whenClauseLabel — pure function unit tests
// ---------------------------------------------------------------------------

describe("whenClauseLabel", () => {
  it("formats array when clause as 'when: A + B'", () => {
    const label = whenClauseLabel(["caddy", "ollama"]);
    expect(label).toBe("when: caddy + ollama");
  });

  it("formats single-element array when clause", () => {
    const label = whenClauseLabel(["traefik"]);
    expect(label).toBe("when: traefik");
  });

  it("formats {any} when clause as 'any: A | B'", () => {
    const label = whenClauseLabel({ any: ["traefik", "caddy"] });
    expect(label).toBe("any: traefik | caddy");
  });

  it("formats single-element {any} when clause", () => {
    const label = whenClauseLabel({ any: ["caddy"] });
    expect(label).toBe("any: caddy");
  });
});
