import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { generatePlan, redactSecrets, formatUnifiedDiff, computeDiffLines, lcsTable } from "../plan.js";
import type { PlanInput, DiffLine } from "../plan.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SIMPLE_COMPOSE = `# Generated by Appbay — do not edit manually
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - "8096:8096"
`;

const CHANGED_COMPOSE = `# Generated by Appbay — do not edit manually
services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.0
    ports:
      - "8096:8096"
    environment:
      - TZ=UTC
`;

const COMPOSE_WITH_SECRETS = `services:
  app:
    image: myapp:latest
    environment:
      - DB_PASSWORD=s3cr3t123
      - API_KEY=hunter2
      - SECRET_TOKEN=mysecrettoken
      - TZ=America/New_York
      - PUID=1000
      - DATABASE_URL=postgres://localhost/db
      - VAULT_SECRET=vault://path/to/secret
`;

// ---------------------------------------------------------------------------
// 1. First deploy (current is null) → status 'new'
// ---------------------------------------------------------------------------

describe("generatePlan", () => {
  it("returns status 'new' with all lines as adds for first deploy", () => {
    const input: PlanInput = {
      appName: "jellyfin",
      rendered: SIMPLE_COMPOSE,
      current: null,
    };

    const plan = generatePlan(input);

    expect(plan.status).toBe("new");
    expect(plan.appName).toBe("jellyfin");
    expect(plan.diff).not.toBeNull();
    expect(plan.diffLines.length).toBeGreaterThan(0);

    // Every line should be an addition.
    for (const line of plan.diffLines) {
      expect(line.type).toBe("add");
    }

    // Diff string should contain '+' prefixed lines (additions).
    expect(plan.diff).toContain("+");

    // No removal lines (lines starting with a single '-' that are not the
    // diff header `--- a/...`).
    const contentLines = plan.diff!.split("\n").filter(
      (l) => !l.startsWith("---") && !l.startsWith("+++"),
    );
    const hasRemovalLines = contentLines.some((l) => l.startsWith("-"));
    expect(hasRemovalLines).toBe(false);
  });

  // -------------------------------------------------------------------------
  // 2. No changes → status 'unchanged', diff is null
  // -------------------------------------------------------------------------

  it("returns status 'unchanged' with null diff when content is identical", () => {
    const input: PlanInput = {
      appName: "jellyfin",
      rendered: SIMPLE_COMPOSE,
      current: SIMPLE_COMPOSE,
    };

    const plan = generatePlan(input);

    expect(plan.status).toBe("unchanged");
    expect(plan.diff).toBeNull();
    expect(plan.diffLines).toHaveLength(0);
  });

  // -------------------------------------------------------------------------
  // 3. Changed compose → status 'changed', diff shows additions/removals
  // -------------------------------------------------------------------------

  it("returns status 'changed' with diff showing additions and removals", () => {
    const input: PlanInput = {
      appName: "jellyfin",
      rendered: CHANGED_COMPOSE,
      current: SIMPLE_COMPOSE,
    };

    const plan = generatePlan(input);

    expect(plan.status).toBe("changed");
    expect(plan.diff).not.toBeNull();

    // Should contain both add and remove lines.
    const hasAdds = plan.diffLines.some((l) => l.type === "add");
    const hasRemoves = plan.diffLines.some((l) => l.type === "remove");
    expect(hasAdds).toBe(true);
    expect(hasRemoves).toBe(true);

    // The image version change should appear in the diff.
    expect(plan.diff).toContain("jellyfin/jellyfin:10.9.0");
    expect(plan.diff).toContain("jellyfin/jellyfin:latest");
  });

  // -------------------------------------------------------------------------
  // 4. Secret values are redacted in diff output
  // -------------------------------------------------------------------------

  it("redacts secret values in diff output", () => {
    const input: PlanInput = {
      appName: "myapp",
      rendered: COMPOSE_WITH_SECRETS,
      current: null,
    };

    const plan = generatePlan(input);

    expect(plan.diff).not.toBeNull();

    // Secret values should be redacted.
    expect(plan.diff).not.toContain("s3cr3t123");
    expect(plan.diff).not.toContain("hunter2");
    expect(plan.diff).not.toContain("mysecrettoken");

    // But the keys should still be visible.
    expect(plan.diff).toContain("DB_PASSWORD=");
    expect(plan.diff).toContain("API_KEY=");
    expect(plan.diff).toContain("SECRET_TOKEN=");

    // Redaction marker should be present.
    expect(plan.diff).toContain("[REDACTED]");
  });

  // -------------------------------------------------------------------------
  // 5. Secret URI patterns (vault://) are redacted
  // -------------------------------------------------------------------------

  it("redacts secret URI patterns like vault://", () => {
    const input: PlanInput = {
      appName: "myapp",
      rendered: COMPOSE_WITH_SECRETS,
      current: null,
    };

    const plan = generatePlan(input);

    expect(plan.diff).not.toBeNull();

    // The vault:// URI should be redacted.
    expect(plan.diff).not.toContain("vault://path/to/secret");

    // The key should still be visible.
    expect(plan.diff).toContain("VAULT_SECRET=");
    expect(plan.diff).toContain("[REDACTED]");
  });

  // -------------------------------------------------------------------------
  // 6. Hash is deterministic for same input
  // -------------------------------------------------------------------------

  it("produces deterministic hash for the same rendered input", () => {
    const input: PlanInput = {
      appName: "jellyfin",
      rendered: SIMPLE_COMPOSE,
      current: null,
    };

    const plan1 = generatePlan(input);
    const plan2 = generatePlan(input);

    expect(plan1.hash).toBe(plan2.hash);

    // Hash should match a manually computed SHA-256.
    const expected = createHash("sha256")
      .update(SIMPLE_COMPOSE)
      .digest("hex");
    expect(plan1.hash).toBe(expected);
  });

  // -------------------------------------------------------------------------
  // 7. Different input produces different hash
  // -------------------------------------------------------------------------

  it("produces different hash for different rendered input", () => {
    const plan1 = generatePlan({
      appName: "jellyfin",
      rendered: SIMPLE_COMPOSE,
      current: null,
    });

    const plan2 = generatePlan({
      appName: "jellyfin",
      rendered: CHANGED_COMPOSE,
      current: null,
    });

    expect(plan1.hash).not.toBe(plan2.hash);
  });

  // -------------------------------------------------------------------------
  // 9. Non-secret env vars are NOT redacted
  // -------------------------------------------------------------------------

  it("does not redact non-secret environment variables", () => {
    const input: PlanInput = {
      appName: "myapp",
      rendered: COMPOSE_WITH_SECRETS,
      current: null,
    };

    const plan = generatePlan(input);

    expect(plan.diff).not.toBeNull();

    // Non-secret values should remain visible.
    expect(plan.diff).toContain("TZ=America/New_York");
    expect(plan.diff).toContain("PUID=1000");
    expect(plan.diff).toContain("DATABASE_URL=postgres://localhost/db");
  });

  // -------------------------------------------------------------------------
  // 10. Removed app → status 'removed'
  // -------------------------------------------------------------------------

  it("returns status 'removed' when rendered is empty and current exists", () => {
    const input: PlanInput = {
      appName: "jellyfin",
      rendered: "",
      current: SIMPLE_COMPOSE,
    };

    const plan = generatePlan(input);

    expect(plan.status).toBe("removed");
    expect(plan.diff).not.toBeNull();
    expect(plan.diffLines.length).toBeGreaterThan(0);

    // Every line should be a removal.
    for (const line of plan.diffLines) {
      expect(line.type).toBe("remove");
    }

    // Diff string should contain '-' prefixed lines.
    expect(plan.diff).toContain("-");
  });
});

// ---------------------------------------------------------------------------
// 8. redactSecrets handles PASSWORD, SECRET, TOKEN, KEY patterns
// ---------------------------------------------------------------------------

describe("redactSecrets", () => {
  it("redacts PASSWORD, SECRET, TOKEN, and KEY patterns", () => {
    const text = [
      "DB_PASSWORD=supersecret",
      "APP_SECRET=hidden",
      "AUTH_TOKEN=tok123",
      "API_KEY=key456",
      "PRIVATE_KEY=pk789",
      "ACCESS_KEY=ak000",
    ].join("\n");

    const redacted = redactSecrets(text);

    expect(redacted).toContain("DB_PASSWORD=[REDACTED]");
    expect(redacted).toContain("APP_SECRET=[REDACTED]");
    expect(redacted).toContain("AUTH_TOKEN=[REDACTED]");
    expect(redacted).toContain("API_KEY=[REDACTED]");
    expect(redacted).toContain("PRIVATE_KEY=[REDACTED]");
    expect(redacted).toContain("ACCESS_KEY=[REDACTED]");

    // Original values should not be present.
    expect(redacted).not.toContain("supersecret");
    expect(redacted).not.toContain("hidden");
    expect(redacted).not.toContain("tok123");
    expect(redacted).not.toContain("key456");
  });

  it("does not redact non-secret env vars", () => {
    const text = [
      "TZ=America/New_York",
      "PUID=1000",
      "PGID=1000",
      "NODE_ENV=production",
    ].join("\n");

    const redacted = redactSecrets(text);

    expect(redacted).toBe(text);
  });

  it("redacts vault:// and sops:// URI values", () => {
    const text = [
      "MY_SECRET=vault://secret/path",
      "OTHER_SECRET=sops://encrypted/path",
    ].join("\n");

    const redacted = redactSecrets(text);

    expect(redacted).toContain("MY_SECRET=[REDACTED]");
    expect(redacted).toContain("OTHER_SECRET=[REDACTED]");
    expect(redacted).not.toContain("vault://");
    expect(redacted).not.toContain("sops://");
  });

  it("redacts long base64-encoded values after = in env vars", () => {
    // 24-char base64 string (above 20 char threshold)
    const text = "SOME_VAR=YWJjZGVmZ2hpamtsbW5vcHFyc3Q=";

    const redacted = redactSecrets(text);

    expect(redacted).toBe("SOME_VAR=[REDACTED]");
  });

  it("applies custom secret patterns when provided", () => {
    const text = "CUSTOM_FIELD=myvalue123";
    const customPattern = /^(CUSTOM_FIELD=).+$/;

    const redacted = redactSecrets(text, [customPattern]);

    expect(redacted).toBe("CUSTOM_FIELD=[REDACTED]");
  });
});

// ---------------------------------------------------------------------------
// formatUnifiedDiff — hunk header correctness
// ---------------------------------------------------------------------------

describe("formatUnifiedDiff hunk headers", () => {
  // ── Hunk headers are present ───────────────────────────────────────────

  it("emits @@ hunk header for a changed diff", () => {
    const oldLines = ["line1", "line2", "line3"];
    const newLines = ["line1", "CHANGED", "line3"];
    const diffLines = computeDiffLines(oldLines, newLines);
    const diff = formatUnifiedDiff("myapp", diffLines);
    expect(diff).toContain("@@");
  });

  it("emits -0,0 for a pure-addition hunk (new file)", () => {
    const diffLines: DiffLine[] = [
      { type: "add", content: "line1" },
      { type: "add", content: "line2" },
      { type: "add", content: "line3" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    expect(diff).toContain("@@ -0,0 +1,3 @@");
  });

  it("emits +0,0 for a pure-removal hunk (removed file)", () => {
    const diffLines: DiffLine[] = [
      { type: "remove", content: "line1" },
      { type: "remove", content: "line2" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    expect(diff).toContain("@@ -1,2 +0,0 @@");
  });

  // ── Correct old/new line accounting ───────────────────────────────────

  it("correctly counts old/new lines in hunk header for a single substitution surrounded by context", () => {
    // 2 context + 1 remove + 1 add + 1 context = 5 lines total
    const diffLines: DiffLine[] = [
      { type: "context", content: "ctx1" },
      { type: "context", content: "ctx2" },
      { type: "remove", content: "old_line" },
      { type: "add", content: "new_line" },
      { type: "context", content: "ctx3" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    // oldCount = ctx1 + ctx2 + old_line + ctx3 = 4, starting at old line 1
    // newCount = ctx1 + ctx2 + new_line + ctx3 = 4, starting at new line 1
    expect(diff).toContain("@@ -1,4 +1,4 @@");
  });

  it("preserves file headers (--- / +++)", () => {
    const diffLines: DiffLine[] = [{ type: "add", content: "x" }];
    const diff = formatUnifiedDiff("jellyfin", diffLines);
    expect(diff).toContain("--- a/jellyfin/docker-compose.rendered.yml");
    expect(diff).toContain("+++ b/jellyfin/docker-compose.rendered.yml");
  });

  // ── Hunk merging and splitting ─────────────────────────────────────────

  it("merges two nearby changes (within 2×contextLines) into a single hunk", () => {
    const diffLines: DiffLine[] = [
      { type: "remove", content: "old_A" },
      { type: "add", content: "new_A" },
      { type: "context", content: "between1" },
      { type: "context", content: "between2" },
      { type: "remove", content: "old_B" },
      { type: "add", content: "new_B" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    const hunkHeaders = diff.split("\n").filter((l) => l.startsWith("@@"));
    expect(hunkHeaders).toHaveLength(1);
  });

  it("produces two separate hunks for changes more than 2×contextLines apart", () => {
    // 20 context lines between changes — far beyond the default 3-line window
    const between: DiffLine[] = Array.from({ length: 20 }, (_, i) => ({
      type: "context" as const,
      content: `ctx_${i}`,
    }));
    const diffLines: DiffLine[] = [
      { type: "remove", content: "old_A" },
      { type: "add", content: "new_A" },
      ...between,
      { type: "remove", content: "old_B" },
      { type: "add", content: "new_B" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    const hunkHeaders = diff.split("\n").filter((l) => l.startsWith("@@"));
    expect(hunkHeaders).toHaveLength(2);
  });

  // ── Context lines appear in output ────────────────────────────────────

  it("includes context lines as space-prefixed in the hunk", () => {
    const diffLines: DiffLine[] = [
      { type: "context", content: "before" },
      { type: "remove", content: "old" },
      { type: "add", content: "new" },
      { type: "context", content: "after" },
    ];
    const diff = formatUnifiedDiff("myapp", diffLines);
    expect(diff).toContain(" before");
    expect(diff).toContain(" after");
  });

  // ── generatePlan integration — hunk headers propagate ─────────────────

  it("generatePlan diff for a changed file contains a @@ hunk header", () => {
    const plan = generatePlan({
      appName: "jellyfin",
      rendered: CHANGED_COMPOSE,
      current: SIMPLE_COMPOSE,
    });
    expect(plan.diff).toContain("@@");
  });

  it("generatePlan diff for a new file contains @@ -0,0 hunk header", () => {
    const plan = generatePlan({
      appName: "jellyfin",
      rendered: SIMPLE_COMPOSE,
      current: null,
    });
    expect(plan.diff).toContain("@@ -0,0 +");
  });

  it("generatePlan diff for a removed app contains +0,0 hunk header", () => {
    const plan = generatePlan({
      appName: "jellyfin",
      rendered: "",
      current: SIMPLE_COMPOSE,
    });
    expect(plan.diff).toContain("+0,0 @@");
  });

  // ── formatUnifiedDiff with all-context (no changed lines) ─────────────
  // Branch: changedIndices.length === 0 → returns only file headers.

  it("returns only file headers when diff has no changed lines (all context)", () => {
    // Construct a diff from identical content — all lines will be context.
    const lines = ["a", "b", "c"];
    const diffLines = computeDiffLines(lines, lines);
    // All context, no adds/removes.
    expect(diffLines.every((l) => l.type === "context")).toBe(true);

    const diff = formatUnifiedDiff("myapp", diffLines);
    // Should contain file headers but no @@ hunk header.
    expect(diff).toContain("--- a/myapp/docker-compose.rendered.yml");
    expect(diff).toContain("+++ b/myapp/docker-compose.rendered.yml");
    expect(diff).not.toContain("@@");
  });
});

// ---------------------------------------------------------------------------
// lcsTable — LCS DP table invariants
// ---------------------------------------------------------------------------

describe("lcsTable", () => {
  it("returns an all-zero table for two empty arrays", () => {
    const table = lcsTable([], []);
    // Should be a 1×1 matrix with only the 0-row and 0-col.
    expect(table).toHaveLength(1);
    expect(table[0]).toHaveLength(1);
    expect(table[0]![0]).toBe(0);
  });

  it("returns an all-zero table when arrays share no common elements", () => {
    const table = lcsTable(["a", "b", "c"], ["x", "y", "z"]);
    // LCS of fully disjoint arrays is 0.
    expect(table[3]![3]).toBe(0);
  });

  it("returns LCS length = array length for two identical arrays", () => {
    const arr = ["line1", "line2", "line3"];
    const table = lcsTable(arr, arr);
    // Diagonal fills up: table[m][n] should equal the array length.
    expect(table[3]![3]).toBe(3);
  });

  it("computes correct LCS length for a known pair", () => {
    // LCS("A", "B", "C", "D") vs ("B", "C", "D", "E") = 3 ("B","C","D")
    const a = ["A", "B", "C", "D"];
    const b = ["B", "C", "D", "E"];
    const table = lcsTable(a, b);
    expect(table[4]![4]).toBe(3);
  });

  it("produces a table with correct dimensions (m+1 × n+1)", () => {
    const a = ["x", "y"];
    const b = ["p", "q", "r"];
    const table = lcsTable(a, b);
    expect(table).toHaveLength(3); // m+1 = 3
    expect(table[0]).toHaveLength(4); // n+1 = 4
  });
});
