import { describe, it, expect } from "vitest";
import { parse } from "yaml";
import {
  renderCompose,
  mergeServiceFragment,
  mergeServicesInto,
  mergeComposeObjects,
  isPlainObject,
} from "../renderer.js";
import type { RenderInput } from "../renderer.js";

// ---------------------------------------------------------------------------
// 1. Simple compose -- no overrides, overlays, or traits
// ---------------------------------------------------------------------------

describe("renderCompose", () => {
  it("renders a simple compose as-is with header comment", () => {
    const input: RenderInput = {
      appName: "jellyfin",
      compose: {
        services: {
          jellyfin: {
            image: "jellyfin/jellyfin:latest",
            ports: ["8096:8096"],
          },
        },
      },
    };

    const result = renderCompose(input);

    // Header comment is present.
    expect(result.compose).toMatch(
      /^# Generated by Appbay — do not edit manually/,
    );

    // Object output matches input services.
    expect(result.composeObject.services).toEqual({
      jellyfin: {
        image: "jellyfin/jellyfin:latest",
        ports: ["8096:8096"],
      },
    });

    // No auxiliary files.
    expect(result.auxiliaryFiles).toHaveLength(0);
  });

  // -------------------------------------------------------------------------
  // 2. Static overrides merged into services
  // -------------------------------------------------------------------------

  it("merges static overrides into services", () => {
    const input: RenderInput = {
      appName: "jellyfin",
      compose: {
        services: {
          jellyfin: {
            image: "jellyfin/jellyfin:latest",
            environment: ["TZ=UTC"],
          },
        },
      },
      overrides: {
        jellyfin: {
          environment: ["JELLYFIN_DATA_DIR=/data"],
          restart: "unless-stopped",
        },
      },
    };

    const result = renderCompose(input);
    const svc = (result.composeObject.services as Record<string, Record<string, unknown>>).jellyfin;

    // Environment arrays are appended.
    expect(svc.environment).toEqual(["TZ=UTC", "JELLYFIN_DATA_DIR=/data"]);

    // Scalar override applied.
    expect(svc.restart).toBe("unless-stopped");
  });

  // -------------------------------------------------------------------------
  // 3. Overlay fragments merged before overrides
  // -------------------------------------------------------------------------

  it("applies overlay fragments before static overrides", () => {
    const input: RenderInput = {
      appName: "webui",
      compose: {
        services: {
          webui: {
            image: "open-webui:latest",
            environment: ["PORT=3000"],
          },
        },
      },
      overlayServices: {
        webui: {
          environment: ["OLLAMA_URL=http://ollama:11434"],
        },
      },
      overrides: {
        webui: {
          environment: ["DEBUG=true"],
        },
      },
    };

    const result = renderCompose(input);
    const svc = (result.composeObject.services as Record<string, Record<string, unknown>>).webui;

    // Merge order: base → overlay → overrides (all appended for arrays).
    expect(svc.environment).toEqual([
      "PORT=3000",
      "OLLAMA_URL=http://ollama:11434",
      "DEBUG=true",
    ]);
  });

  // -------------------------------------------------------------------------
  // 4. Trait modifications applied
  // -------------------------------------------------------------------------

  it("applies trait compose modifications", () => {
    const input: RenderInput = {
      appName: "jellyfin",
      compose: {
        services: {
          jellyfin: {
            image: "jellyfin/jellyfin:latest",
            labels: { "app.name": "jellyfin" },
          },
        },
        networks: {},
      },
      traitCompose: {
        services: {
          jellyfin: {
            labels: {
              "traefik.enable": "true",
              "traefik.http.routers.jellyfin.rule": "Host(`jellyfin.local`)",
            },
          },
        },
        networks: {
          traefik_net: { external: true },
        },
      },
    };

    const result = renderCompose(input);
    const svc = (result.composeObject.services as Record<string, Record<string, unknown>>).jellyfin;

    // Labels are shallow-merged.
    expect(svc.labels).toEqual({
      "app.name": "jellyfin",
      "traefik.enable": "true",
      "traefik.http.routers.jellyfin.rule": "Host(`jellyfin.local`)",
    });

    // Networks are merged at top level.
    const nets = result.composeObject.networks as Record<string, unknown>;
    expect(nets.traefik_net).toEqual({ external: true });
  });

  // -------------------------------------------------------------------------
  // 5. Full pipeline: base + overlays + traits + overrides
  // -------------------------------------------------------------------------

  it("merges base + overlays + traits + overrides in correct order", () => {
    const input: RenderInput = {
      appName: "myapp",
      compose: {
        services: {
          web: {
            image: "myapp:latest",
            environment: ["NODE_ENV=production"],
            ports: ["3000:3000"],
            labels: { version: "1.0" },
          },
        },
      },
      overlayServices: {
        web: {
          environment: ["REDIS_URL=redis://redis:6379"],
          depends_on: { redis: { condition: "service_started" } },
        },
        redis: {
          image: "redis:7",
        },
      },
      traitCompose: {
        services: {
          web: {
            labels: { "traefik.enable": "true" },
            volumes: ["/certs:/certs:ro"],
          },
        },
      },
      overrides: {
        web: {
          environment: ["LOG_LEVEL=debug"],
          ports: ["3001:3001"],
        },
      },
    };

    const result = renderCompose(input);
    const svcs = result.composeObject.services as Record<string, Record<string, unknown>>;

    // Base service exists with all layers merged.
    const web = svcs.web;
    expect(web.image).toBe("myapp:latest");

    // Environment: base + overlay + override (traits didn't add env).
    expect(web.environment).toEqual([
      "NODE_ENV=production",
      "REDIS_URL=redis://redis:6379",
      "LOG_LEVEL=debug",
    ]);

    // Ports: base + trait (none) + override.
    expect(web.ports).toEqual(["3000:3000", "3001:3001"]);

    // Labels: base shallow-merged with trait.
    expect(web.labels).toEqual({
      version: "1.0",
      "traefik.enable": "true",
    });

    // depends_on from overlay.
    expect(web.depends_on).toEqual({ redis: { condition: "service_started" } });

    // Volumes from trait.
    expect(web.volumes).toEqual(["/certs:/certs:ro"]);

    // New service from overlay.
    expect(svcs.redis).toEqual({ image: "redis:7" });
  });

  // -------------------------------------------------------------------------
  // 6. Auxiliary files collected in output
  // -------------------------------------------------------------------------

  it("collects auxiliary files in output", () => {
    const auxFiles = [
      { path: "traefik/dynamic/jellyfin.yml", content: "http:\n  routers: {}" },
      { path: ".env", content: "FOO=bar" },
    ];

    const input: RenderInput = {
      appName: "jellyfin",
      compose: {
        services: { jellyfin: { image: "jellyfin:latest" } },
      },
      auxiliaryFiles: auxFiles,
    };

    const result = renderCompose(input);

    expect(result.auxiliaryFiles).toHaveLength(2);
    expect(result.auxiliaryFiles[0].path).toBe("traefik/dynamic/jellyfin.yml");
    expect(result.auxiliaryFiles[1].content).toBe("FOO=bar");

    // Auxiliary files are a copy, not the same reference.
    expect(result.auxiliaryFiles).not.toBe(auxFiles);
  });

  // -------------------------------------------------------------------------
  // 7. YAML output is valid (round-trips through parse)
  // -------------------------------------------------------------------------

  it("produces valid YAML that round-trips through parse", () => {
    const input: RenderInput = {
      appName: "roundtrip",
      compose: {
        services: {
          app: {
            image: "myapp:latest",
            environment: ["KEY=value with spaces", "MULTI=a=b=c"],
            ports: ["8080:80"],
            volumes: ["./data:/data"],
            labels: { "com.example/note": "hello world" },
          },
        },
        networks: {
          internal: { driver: "bridge" },
        },
        volumes: {
          data: {},
        },
      },
    };

    const result = renderCompose(input);

    // Parse the YAML output back into an object.
    const parsed = parse(result.compose);

    // The parsed output should match the compose object (minus the header).
    expect(parsed).toEqual(result.composeObject);
  });

  // -------------------------------------------------------------------------
  // 8. Empty services in overrides don't corrupt compose
  // -------------------------------------------------------------------------

  it("adds new top-level service from traitCompose when base has no such service", () => {
    // Covers the `else: merged[svcName] = svcDef` branch in mergeComposeObjects
    // services loop — when the service exists in overlay but not in base.
    const input: RenderInput = {
      appName: "myapp",
      compose: {
        services: {
          web: { image: "myapp:latest" },
        },
      },
      traitCompose: {
        services: {
          "web-init-hook": { image: "busybox:latest", restart: "no" },
        },
      },
    };

    const result = renderCompose(input);
    const svcs = result.composeObject.services as Record<string, Record<string, unknown>>;
    expect(svcs["web-init-hook"]).toBeDefined();
    expect(svcs["web-init-hook"].image).toBe("busybox:latest");
    expect(svcs.web.image).toBe("myapp:latest");
  });

  it("skips empty override fragments without corrupting compose", () => {
    const input: RenderInput = {
      appName: "clean",
      compose: {
        services: {
          app: {
            image: "myapp:latest",
            environment: ["FOO=bar"],
          },
        },
      },
      overrides: {
        app: {},
        nonexistent: {},
      },
      overlayServices: {
        app: {},
      },
    };

    const result = renderCompose(input);
    const svcs = result.composeObject.services as Record<string, Record<string, unknown>>;

    // Original service is untouched.
    expect(svcs.app).toEqual({
      image: "myapp:latest",
      environment: ["FOO=bar"],
    });

    // No phantom service created from empty fragment.
    expect(svcs.nonexistent).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// Helper unit tests
// ---------------------------------------------------------------------------

describe("isPlainObject", () => {
  it("returns true for plain objects", () => {
    expect(isPlainObject({ a: 1 })).toBe(true);
    expect(isPlainObject({})).toBe(true);
  });

  it("returns false for arrays", () => {
    expect(isPlainObject([])).toBe(false);
  });

  it("returns false for null", () => {
    expect(isPlainObject(null)).toBe(false);
  });

  it("returns false for primitives", () => {
    expect(isPlainObject("string")).toBe(false);
    expect(isPlainObject(42)).toBe(false);
    expect(isPlainObject(undefined)).toBe(false);
  });
});

describe("mergeServiceFragment", () => {
  it("uses empty array when fragmentValue for APPEND_ARRAY_KEYS key is not an array", () => {
    // Covers the `Array.isArray(fragmentValue) ? fragmentValue : []` branch
    // when someone provides a non-array value for environment/volumes/ports.
    const base = { environment: ["BASE=1"] };
    // Cast to bypass TS — simulates a badly-shaped fragment at runtime.
    const frag = { environment: "BAD_STRING" as unknown as string[] };
    const result = mergeServiceFragment(base, frag);
    // Base array + empty fragment array → base unchanged (BAD_STRING discarded).
    expect(result.environment).toEqual(["BASE=1"]);
  });

  it("uses empty object when fragmentValue for MERGE_OBJECT_KEYS key is not a plain object", () => {
    // Covers the `isPlainObject(fragmentValue) ? fragmentValue : {}` branch.
    const base = { depends_on: { redis: { condition: "service_started" } } };
    const frag = { depends_on: null as unknown as Record<string, unknown> };
    const result = mergeServiceFragment(base, frag);
    // Base object + empty fragment object → base preserved.
    expect(result.depends_on).toEqual({ redis: { condition: "service_started" } });
  });

  it("recursively merges nested plain objects for non-special keys", () => {
    // Covers the `isPlainObject(baseValue) && isPlainObject(fragmentValue)` branch —
    // nested objects like `deploy.resources.limits` get deep-merged.
    const base = { deploy: { resources: { limits: { memory: "512m" } } } };
    const frag = { deploy: { resources: { limits: { cpus: "0.5" } } } };
    const result = mergeServiceFragment(base, frag as Record<string, unknown>);
    const limits = (result.deploy as Record<string, unknown>).resources as Record<string, unknown>;
    expect((limits.limits as Record<string, unknown>).memory).toBe("512m");
    expect((limits.limits as Record<string, unknown>).cpus).toBe("0.5");
  });
});

describe("mergeServicesInto", () => {
  it("starts from empty services when compose.services is not a plain object", () => {
    // Covers the `isPlainObject(compose.services) ? ... : {}` fallback.
    const compose = { services: null as unknown as Record<string, unknown> };
    const result = mergeServicesInto(compose, {
      web: { image: "nginx:latest" },
    });
    const svcs = result.services as Record<string, unknown>;
    expect(svcs.web).toEqual({ image: "nginx:latest" });
  });
});
