/**
 * Supported authentication trait: Caddy Security portal plus authorization policy.
 *
 * The previous forward-auth implementation is retained only under the legacy quarantine
 * and is not imported by the supported trait registry.
 */

import { AuthTraitSchema } from "../../schemas/appbay-yaml.js";
import type { AuthTrait } from "../../schemas/appbay-yaml.js";
import type {
  TraitDefinition,
  TraitTransformInput,
  TraitTransformOutput,
} from "../types.js";

function safePolicyName(appName: string): string {
  return `appbay_${appName.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function ingressHost(input: TraitTransformInput): string | null {
  const ingress = input.siblingTraits.find((trait) => trait.type === "ingress");
  const host = typeof ingress?.host === "string" ? ingress.host.trim() : "";
  return host || null;
}

export function caddySecurityPolicy(
  appName: string,
  host: string,
  policy: AuthTrait["policy"],
  group?: string,
): string {
  const roles = group
    ? [`authp/admin`, group.startsWith("authp/") ? group : `authp/${group}`]
    : ["authp/admin", "authp/user"];
  const access =
    policy === "deny" ? "deny" : `allow roles ${[...new Set(roles)].join(" ")}`;

  return [
    "# Generated by AppBay — do not edit manually",
    `authorization policy ${safePolicyName(appName)} {`,
    `\tset auth url https://${host}/auth`,
    "\tcrypto key verify {$APPBAY_EDGE_TOKEN_SECRET}",
    `\t${access}`,
    "\tenable strip token",
    "\tinject header \"Remote-User\" from sub",
    "\tinject header \"Remote-Email\" from email",
    "\tinject header \"Remote-Groups\" from roles",
    "}",
    "",
  ].join("\n");
}

export function caddySecurityRoute(appName: string): string {
  return [
    "# Generated by AppBay — do not edit manually",
    "route /auth* {",
    "\tauthenticate * with appbay_portal",
    "}",
    `authorize with ${safePolicyName(appName)}`,
    "",
  ].join("\n");
}

export const authTraitDefinition: TraitDefinition<"auth"> = {
  type: "auth",
  category: "core",
  scope: "app",
  conflictsWith: [],
  description: "Caddy Security browser login and role-based authorization.",
  schema: AuthTraitSchema,
  transform(input: TraitTransformInput): TraitTransformOutput {
    const props = input.properties as AuthTrait;
    if (!props.enabled) return { compose: input.compose };

    if (input.context.ingressProvider !== "caddy") {
      return {
        compose: input.compose,
        errors: [
          "The auth trait requires the Caddy Security edge. Re-run `appbay init " +
            "--ingress-provider caddy`; Traefik remains supported for ingress but is not " +
            "an authentication provider.",
        ],
      };
    }

    const host = ingressHost(input);
    if (!host) {
      return {
        compose: input.compose,
        errors: ["The auth trait requires a sibling ingress trait with a non-empty host."],
      };
    }

    return {
      compose: input.compose,
      auxiliaryFiles: [
        {
          path: `etc/apps/caddy/config/dynamic/auth/${input.app}-security.caddy`,
          content: caddySecurityRoute(input.app),
        },
        {
          path: `etc/apps/caddy/config/security/policies/${input.app}.caddy`,
          content: caddySecurityPolicy(input.app, host, props.policy, props.group),
        },
      ],
      metadata: {
        authProvider: "caddy-security",
        app: input.app,
        domain: host,
        policy: props.policy,
        group: props.group,
      },
    };
  },
};
