/**
 * Tests for `appbay init --container-runtime` applied to an EXISTING install.
 *
 * WHY THIS PATH MATTERS MORE THAN THE FRESH-INSTALL ONE: a configuration
 * management run (Ansible, in the case this was written for) re-runs `appbay
 * init` on a host that is already initialised, every time it converges. That is
 * the normal case, not the exception — and `writeProjectConfig` returns early
 * when project.yaml exists, so without `upsertContainerRuntime` the flag would
 * be silently dropped on precisely the hosts that matter.
 *
 * The three-way return is the other half: a CLI invocation is not idempotent in
 * Ansible's sense, so the caller must derive changed-state from a READ-BACK
 * rather than from an exit code. "created" | "updated" | "unchanged" is that
 * read-back.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseInstanceConfig } from "@appbay/core";
import { upsertContainerRuntime } from "../init.js";

let home: string;
const configPath = () => join(home, "project.yaml");

beforeEach(() => {
  home = join(tmpdir(), `appbay-init-rt-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(home, { recursive: true });
});

afterEach(() => {
  rmSync(home, { recursive: true, force: true });
});

describe("upsertContainerRuntime", () => {
  it("adds the key to a config that lacks it", async () => {
    writeFileSync(configPath(), "project: demo\ndomain: local\n", "utf-8");

    expect(await upsertContainerRuntime(home, "podman")).toBe("created");
    expect(parseInstanceConfig(readFileSync(configPath(), "utf-8")).container_runtime).toBe("podman");
  });

  it("reports unchanged when the value already matches — the second converge", async () => {
    writeFileSync(configPath(), "project: demo\ncontainer_runtime: podman\n", "utf-8");

    expect(await upsertContainerRuntime(home, "podman")).toBe("unchanged");
  });

  it("does not rewrite the file when nothing changes", async () => {
    const original = "project: demo\ncontainer_runtime: podman\n";
    writeFileSync(configPath(), original, "utf-8");

    await upsertContainerRuntime(home, "podman");
    // Byte-for-byte. A no-op that still rewrites the file churns mtime and makes
    // every converge look like a change to anything watching the path.
    expect(readFileSync(configPath(), "utf-8")).toBe(original);
  });

  it("switches an existing value", async () => {
    writeFileSync(configPath(), "project: demo\ncontainer_runtime: docker\n", "utf-8");

    expect(await upsertContainerRuntime(home, "podman")).toBe("updated");
    expect(parseInstanceConfig(readFileSync(configPath(), "utf-8")).container_runtime).toBe("podman");
  });

  it("preserves comments and unrelated keys", async () => {
    writeFileSync(
      configPath(),
      `# Appbay project configuration — generated by "appbay init"\n` +
        `project: demo\ndomain: example.com\ncatalog_source: /opt/catalog\ncontainer_runtime: docker\n`,
      "utf-8",
    );

    await upsertContainerRuntime(home, "podman");
    const text = readFileSync(configPath(), "utf-8");

    expect(text).toContain(`# Appbay project configuration`);
    const cfg = parseInstanceConfig(text);
    expect(cfg.project).toBe("demo");
    expect(cfg.domain).toBe("example.com");
    expect(cfg.catalog_source).toBe("/opt/catalog");
    expect(cfg.container_runtime).toBe("podman");
  });

  it("writes the key exactly once when applied repeatedly", async () => {
    writeFileSync(configPath(), "project: demo\n", "utf-8");

    await upsertContainerRuntime(home, "podman");
    await upsertContainerRuntime(home, "docker");
    await upsertContainerRuntime(home, "podman");

    const occurrences = readFileSync(configPath(), "utf-8")
      .split("\n")
      .filter((l) => l.startsWith("container_runtime:")).length;
    expect(occurrences).toBe(1);
  });

  it("records the default explicitly rather than leaving it implicit", async () => {
    // Setting docker when the key is absent is NOT a no-op: an unstated runtime
    // reads as "unknown" to the next operator, and the point of the flag is to
    // make the choice auditable.
    writeFileSync(configPath(), "project: demo\n", "utf-8");

    expect(await upsertContainerRuntime(home, "docker")).toBe("created");
    expect(parseInstanceConfig(readFileSync(configPath(), "utf-8")).container_runtime).toBe("docker");
  });

  it("appends cleanly to a file with no trailing newline", async () => {
    writeFileSync(configPath(), "project: demo", "utf-8");

    await upsertContainerRuntime(home, "podman");
    const cfg = parseInstanceConfig(readFileSync(configPath(), "utf-8"));
    expect(cfg.project).toBe("demo");
    expect(cfg.container_runtime).toBe("podman");
  });
});
